//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.compromisototal.webservice.autogenerado.asicom;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "wsCCLaAraucanaInfoCredito", targetNamespace = "http://server.laaraucana.ws.asicom/", wsdlLocation = "WEB-INF/wsdl/wsCCLaAraucanaInfoCredito.wsdl")
public class WsCCLaAraucanaInfoCredito_Service
    extends Service
{

    private final static URL WSCCLAARAUCANAINFOCREDITO_WSDL_LOCATION;
    private final static WebServiceException WSCCLAARAUCANAINFOCREDITO_EXCEPTION;
    private final static QName WSCCLAARAUCANAINFOCREDITO_QNAME = new QName("http://server.laaraucana.ws.asicom/", "wsCCLaAraucanaInfoCredito");

    static {
            WSCCLAARAUCANAINFOCREDITO_WSDL_LOCATION = cl.laaraucana.compromisototal.webservice.autogenerado.asicom.WsCCLaAraucanaInfoCredito_Service.class.getResource("/WEB-INF/wsdl/wsCCLaAraucanaInfoCredito.wsdl");
        WebServiceException e = null;
        if (WSCCLAARAUCANAINFOCREDITO_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/wsCCLaAraucanaInfoCredito.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSCCLAARAUCANAINFOCREDITO_EXCEPTION = e;
    }

    public WsCCLaAraucanaInfoCredito_Service() {
        super(__getWsdlLocation(), WSCCLAARAUCANAINFOCREDITO_QNAME);
    }

    public WsCCLaAraucanaInfoCredito_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCCLAARAUCANAINFOCREDITO_QNAME, features);
    }

    public WsCCLaAraucanaInfoCredito_Service(URL wsdlLocation) {
        super(wsdlLocation, WSCCLAARAUCANAINFOCREDITO_QNAME);
    }

    public WsCCLaAraucanaInfoCredito_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCCLAARAUCANAINFOCREDITO_QNAME, features);
    }

    public WsCCLaAraucanaInfoCredito_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsCCLaAraucanaInfoCredito_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsCCLaAraucanaInfoCredito
     */
    @WebEndpoint(name = "wsCCLaAraucanaInfoCreditoPort")
    public WsCCLaAraucanaInfoCredito getWsCCLaAraucanaInfoCreditoPort() {
        return super.getPort(new QName("http://server.laaraucana.ws.asicom/", "wsCCLaAraucanaInfoCreditoPort"), WsCCLaAraucanaInfoCredito.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsCCLaAraucanaInfoCredito
     */
    @WebEndpoint(name = "wsCCLaAraucanaInfoCreditoPort")
    public WsCCLaAraucanaInfoCredito getWsCCLaAraucanaInfoCreditoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.laaraucana.ws.asicom/", "wsCCLaAraucanaInfoCreditoPort"), WsCCLaAraucanaInfoCredito.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCCLAARAUCANAINFOCREDITO_EXCEPTION!= null) {
            throw WSCCLAARAUCANAINFOCREDITO_EXCEPTION;
        }
        return WSCCLAARAUCANAINFOCREDITO_WSDL_LOCATION;
    }

}
