//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.pagoenexceso.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "consultarPagoEnExcesoResponse", namespace = "http://service.pagoenexceso.laaraucana.cl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarPagoEnExcesoResponse", namespace = "http://service.pagoenexceso.laaraucana.cl/")
public class ConsultarPagoEnExcesoResponse {

    @XmlElement(name = "return", namespace = "")
    private cl.laaraucana.pagoenexceso.persistencia.vo.ConsultaPagoEnExcesoOut _return;

    /**
     * 
     * @return
     *     returns ConsultaPagoEnExcesoOut
     */
    public cl.laaraucana.pagoenexceso.persistencia.vo.ConsultaPagoEnExcesoOut getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(cl.laaraucana.pagoenexceso.persistencia.vo.ConsultaPagoEnExcesoOut _return) {
        this._return = _return;
    }

}
