//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.compromisototal.webservice.autogenerado.asicom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "wsCCLaAraucanaInfoCredito", targetNamespace = "http://server.laaraucana.ws.asicom/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsCCLaAraucanaInfoCredito {


    /**
     * 
     * @param rut
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosCredito", targetNamespace = "http://server.laaraucana.ws.asicom/", className = "cl.laaraucana.compromisototal.integracion.asicom.GetDatosCredito")
    @ResponseWrapper(localName = "getDatosCreditoResponse", targetNamespace = "http://server.laaraucana.ws.asicom/", className = "cl.laaraucana.compromisototal.integracion.asicom.GetDatosCreditoResponse")
    @Action(input = "http://server.laaraucana.ws.asicom/wsCCLaAraucanaInfoCredito/getDatosCreditoRequest", output = "http://server.laaraucana.ws.asicom/wsCCLaAraucanaInfoCredito/getDatosCreditoResponse")
    public String getDatosCredito(
        @WebParam(name = "rut", targetNamespace = "")
        String rut);

    /**
     * 
     * @param operacion
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDetalleCredito", targetNamespace = "http://server.laaraucana.ws.asicom/", className = "cl.laaraucana.compromisototal.integracion.asicom.GetDetalleCredito")
    @ResponseWrapper(localName = "getDetalleCreditoResponse", targetNamespace = "http://server.laaraucana.ws.asicom/", className = "cl.laaraucana.compromisototal.integracion.asicom.GetDetalleCreditoResponse")
    @Action(input = "http://server.laaraucana.ws.asicom/wsCCLaAraucanaInfoCredito/getDetalleCreditoRequest", output = "http://server.laaraucana.ws.asicom/wsCCLaAraucanaInfoCredito/getDetalleCreditoResponse")
    public String getDetalleCredito(
        @WebParam(name = "operacion", targetNamespace = "")
        String operacion);

}
