//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.satelites.integracion.ConsultaCreditosARepactarPorRutEnAs400;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ConsultaCreditosARepactarPorRutAs400Service", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", wsdlLocation = "WEB-INF/wsdl/ConsultaCreditosARepactarPorRutAs400.wsdl")
public class ConsultaCreditosARepactarPorRutAs400Service
    extends Service
{

    private final static URL CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_EXCEPTION;
    private final static QName CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_QNAME = new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "ConsultaCreditosARepactarPorRutAs400Service");

    static {
            CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_WSDL_LOCATION = cl.laaraucana.satelites.integracion.ConsultaCreditosARepactarPorRutEnAs400.ConsultaCreditosARepactarPorRutAs400Service.class.getResource("/WEB-INF/wsdl/ConsultaCreditosARepactarPorRutAs400.wsdl");
        WebServiceException e = null;
        if (CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/ConsultaCreditosARepactarPorRutAs400.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_EXCEPTION = e;
    }

    public ConsultaCreditosARepactarPorRutAs400Service() {
        super(__getWsdlLocation(), CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_QNAME);
    }

    public ConsultaCreditosARepactarPorRutAs400Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_QNAME, features);
    }

    public ConsultaCreditosARepactarPorRutAs400Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_QNAME);
    }

    public ConsultaCreditosARepactarPorRutAs400Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_QNAME, features);
    }

    public ConsultaCreditosARepactarPorRutAs400Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCreditosARepactarPorRutAs400Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaCreditosARepactarPorRutAs400
     */
    @WebEndpoint(name = "ConsultaCreditosARepactarPorRutAs400Port")
    public ConsultaCreditosARepactarPorRutAs400 getConsultaCreditosARepactarPorRutAs400Port() {
        return super.getPort(new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "ConsultaCreditosARepactarPorRutAs400Port"), ConsultaCreditosARepactarPorRutAs400.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaCreditosARepactarPorRutAs400
     */
    @WebEndpoint(name = "ConsultaCreditosARepactarPorRutAs400Port")
    public ConsultaCreditosARepactarPorRutAs400 getConsultaCreditosARepactarPorRutAs400Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "ConsultaCreditosARepactarPorRutAs400Port"), ConsultaCreditosARepactarPorRutAs400.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_EXCEPTION!= null) {
            throw CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_EXCEPTION;
        }
        return CONSULTACREDITOSAREPACTARPORRUTAS400SERVICE_WSDL_LOCATION;
    }

}
