//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.satelites.integracion.ConsultaCreditosARepactarPorRutEnAs400;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.laaraucana.satelites.integracion.ConsultaCreditosARepactarPorRutEnAs400 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConsultaCreditosARepactarPorRutAs400Response_QNAME = new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "consultaCreditosARepactarPorRutAs400Response");
    private final static QName _ConsultaCreditosARepactarPorRutAs400_QNAME = new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "consultaCreditosARepactarPorRutAs400");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.laaraucana.satelites.integracion.ConsultaCreditosARepactarPorRutEnAs400
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultaCreditosARepactarPorRutAs400Response }
     * 
     */
    public ConsultaCreditosARepactarPorRutAs400Response createConsultaCreditosARepactarPorRutAs400Response() {
        return new ConsultaCreditosARepactarPorRutAs400Response();
    }

    /**
     * Create an instance of {@link ConsultaCreditosARepactarPorRutAs400_Type }
     * 
     */
    public ConsultaCreditosARepactarPorRutAs400_Type createConsultaCreditosARepactarPorRutAs400_Type() {
        return new ConsultaCreditosARepactarPorRutAs400_Type();
    }

    /**
     * Create an instance of {@link ConsultaCreditosARepactarPorRutAs400SalidaVO }
     * 
     */
    public ConsultaCreditosARepactarPorRutAs400SalidaVO createConsultaCreditosARepactarPorRutAs400SalidaVO() {
        return new ConsultaCreditosARepactarPorRutAs400SalidaVO();
    }

    /**
     * Create an instance of {@link ConsultaCreditosARepactarPorRutAs400EntradaVO }
     * 
     */
    public ConsultaCreditosARepactarPorRutAs400EntradaVO createConsultaCreditosARepactarPorRutAs400EntradaVO() {
        return new ConsultaCreditosARepactarPorRutAs400EntradaVO();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link ConsultaCreditosARepactarPorRutAs400ListaSalidaVO }
     * 
     */
    public ConsultaCreditosARepactarPorRutAs400ListaSalidaVO createConsultaCreditosARepactarPorRutAs400ListaSalidaVO() {
        return new ConsultaCreditosARepactarPorRutAs400ListaSalidaVO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaCreditosARepactarPorRutAs400Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", name = "consultaCreditosARepactarPorRutAs400Response")
    public JAXBElement<ConsultaCreditosARepactarPorRutAs400Response> createConsultaCreditosARepactarPorRutAs400Response(ConsultaCreditosARepactarPorRutAs400Response value) {
        return new JAXBElement<ConsultaCreditosARepactarPorRutAs400Response>(_ConsultaCreditosARepactarPorRutAs400Response_QNAME, ConsultaCreditosARepactarPorRutAs400Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaCreditosARepactarPorRutAs400_Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", name = "consultaCreditosARepactarPorRutAs400")
    public JAXBElement<ConsultaCreditosARepactarPorRutAs400_Type> createConsultaCreditosARepactarPorRutAs400(ConsultaCreditosARepactarPorRutAs400_Type value) {
        return new JAXBElement<ConsultaCreditosARepactarPorRutAs400_Type>(_ConsultaCreditosARepactarPorRutAs400_QNAME, ConsultaCreditosARepactarPorRutAs400_Type.class, null, value);
    }

}
