//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.satelites.integracion.consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400 {


    /**
     * 
     * @param arg0
     * @return
     *     returns cl.laaraucana.satelites.integracion.consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400.ConsultaCuotasCreditoPartidasAbiertaPorFolioSalidaVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", className = "cl.laaraucana.satelites.integracion.consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400.ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_Type")
    @ResponseWrapper(localName = "consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", className = "cl.laaraucana.satelites.integracion.consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400.ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response")
    @Action(input = "http://delegate.toAS.legados.integracion.laaraucana.cl/ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400/consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Request", output = "http://delegate.toAS.legados.integracion.laaraucana.cl/ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400/consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response")
    public ConsultaCuotasCreditoPartidasAbiertaPorFolioSalidaVO consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400(
        @WebParam(name = "arg0", targetNamespace = "")
        ConsultaCuotasCreditoPartidasAbiertasPorFolioEntradaVO arg0);

}
