//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.satelites.integracion.consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.laaraucana.satelites.integracion.consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response_QNAME = new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response");
    private final static QName _ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_QNAME = new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.laaraucana.satelites.integracion.consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_Type }
     * 
     */
    public ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_Type createConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_Type() {
        return new ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_Type();
    }

    /**
     * Create an instance of {@link ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response }
     * 
     */
    public ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response createConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response() {
        return new ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response();
    }

    /**
     * Create an instance of {@link ConsultaCuotasCreditoPartidasAbiertaPorFolioSalidaVO }
     * 
     */
    public ConsultaCuotasCreditoPartidasAbiertaPorFolioSalidaVO createConsultaCuotasCreditoPartidasAbiertaPorFolioSalidaVO() {
        return new ConsultaCuotasCreditoPartidasAbiertaPorFolioSalidaVO();
    }

    /**
     * Create an instance of {@link ConsultaCuotasCreditoPartidasAbiertasPorFolioEntradaVO }
     * 
     */
    public ConsultaCuotasCreditoPartidasAbiertasPorFolioEntradaVO createConsultaCuotasCreditoPartidasAbiertasPorFolioEntradaVO() {
        return new ConsultaCuotasCreditoPartidasAbiertasPorFolioEntradaVO();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link DetalleConsultaCuotasCreditoPartidasAbiertaPorFolioSalidaVO }
     * 
     */
    public DetalleConsultaCuotasCreditoPartidasAbiertaPorFolioSalidaVO createDetalleConsultaCuotasCreditoPartidasAbiertaPorFolioSalidaVO() {
        return new DetalleConsultaCuotasCreditoPartidasAbiertaPorFolioSalidaVO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", name = "consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response")
    public JAXBElement<ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response> createConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response(ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response value) {
        return new JAXBElement<ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response>(_ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response_QNAME, ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", name = "consultaCuotasCreditoPartidasAbiertasPorFolioEnAs400")
    public JAXBElement<ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_Type> createConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400(ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_Type value) {
        return new JAXBElement<ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_Type>(_ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_QNAME, ConsultaCuotasCreditoPartidasAbiertasPorFolioEnAs400_Type.class, null, value);
    }

}
