//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/")
package cl.laaraucana.satelites.integracion.ConsultaCreditosPorRutEnAs400;
