//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.satelites.integracion.ConsultaDatosPagosCreditosPorFolioAs400;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ConsultaDatosPagosCreditosPorFolioAs400Service", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", wsdlLocation = "WEB-INF/wsdl/ConsultaDatosPagosCreditosPorFolioAs400.wsdl")
public class ConsultaDatosPagosCreditosPorFolioAs400Service
    extends Service
{

    private final static URL CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_EXCEPTION;
    private final static QName CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_QNAME = new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "ConsultaDatosPagosCreditosPorFolioAs400Service");

    static {
            CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_WSDL_LOCATION = cl.laaraucana.satelites.integracion.ConsultaDatosPagosCreditosPorFolioAs400.ConsultaDatosPagosCreditosPorFolioAs400Service.class.getResource("/WEB-INF/wsdl/ConsultaDatosPagosCreditosPorFolioAs400.wsdl");
        WebServiceException e = null;
        if (CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/ConsultaDatosPagosCreditosPorFolioAs400.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_EXCEPTION = e;
    }

    public ConsultaDatosPagosCreditosPorFolioAs400Service() {
        super(__getWsdlLocation(), CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_QNAME);
    }

    public ConsultaDatosPagosCreditosPorFolioAs400Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_QNAME, features);
    }

    public ConsultaDatosPagosCreditosPorFolioAs400Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_QNAME);
    }

    public ConsultaDatosPagosCreditosPorFolioAs400Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_QNAME, features);
    }

    public ConsultaDatosPagosCreditosPorFolioAs400Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaDatosPagosCreditosPorFolioAs400Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaDatosPagosCreditosPorFolioAs400
     */
    @WebEndpoint(name = "ConsultaDatosPagosCreditosPorFolioAs400Port")
    public ConsultaDatosPagosCreditosPorFolioAs400 getConsultaDatosPagosCreditosPorFolioAs400Port() {
        return super.getPort(new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "ConsultaDatosPagosCreditosPorFolioAs400Port"), ConsultaDatosPagosCreditosPorFolioAs400.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaDatosPagosCreditosPorFolioAs400
     */
    @WebEndpoint(name = "ConsultaDatosPagosCreditosPorFolioAs400Port")
    public ConsultaDatosPagosCreditosPorFolioAs400 getConsultaDatosPagosCreditosPorFolioAs400Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "ConsultaDatosPagosCreditosPorFolioAs400Port"), ConsultaDatosPagosCreditosPorFolioAs400.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_EXCEPTION!= null) {
            throw CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_EXCEPTION;
        }
        return CONSULTADATOSPAGOSCREDITOSPORFOLIOAS400SERVICE_WSDL_LOCATION;
    }

}
