//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.satelites.integracion.ConsultaDatosPagosCreditosPorFolioAs400;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ConsultaDatosPagosCreditosPorFolioAs400", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaDatosPagosCreditosPorFolioAs400 {


    /**
     * 
     * @param arg0
     * @return
     *     returns cl.laaraucana.satelites.integracion.ConsultaDatosPagosCreditosPorFolioAs400.ConsultaDatosPagosCreditosPorFolioAs400ListaSalidaVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDatosPagosCreditosPorFolioAs400", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", className = "cl.laaraucana.satelites.integracion.ConsultaDatosPagosCreditosPorFolioAs400.ConsultaDatosPagosCreditosPorFolioAs400_Type")
    @ResponseWrapper(localName = "consultaDatosPagosCreditosPorFolioAs400Response", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", className = "cl.laaraucana.satelites.integracion.ConsultaDatosPagosCreditosPorFolioAs400.ConsultaDatosPagosCreditosPorFolioAs400Response")
    @Action(input = "http://delegate.toAS.legados.integracion.laaraucana.cl/ConsultaDatosPagosCreditosPorFolioAs400/consultaDatosPagosCreditosPorFolioAs400Request", output = "http://delegate.toAS.legados.integracion.laaraucana.cl/ConsultaDatosPagosCreditosPorFolioAs400/consultaDatosPagosCreditosPorFolioAs400Response")
    public ConsultaDatosPagosCreditosPorFolioAs400ListaSalidaVO consultaDatosPagosCreditosPorFolioAs400(
        @WebParam(name = "arg0", targetNamespace = "")
        ConsultaDatosPagosCreditosPorFolioAs400EntradaVO arg0);

}
