//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.satelites.integracion.ConsultaFolioFormulario24;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ConsultaFolioFormulario24", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaFolioFormulario24 {


    /**
     * 
     * @param arg0
     * @return
     *     returns cl.laaraucana.satelites.integracion.ConsultaFolioFormulario24.ConsultaFolioFormulario24SalidaVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaFolioFormulario24", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", className = "cl.laaraucana.satelites.integracion.ConsultaFolioFormulario24.ConsultaFolioFormulario24_Type")
    @ResponseWrapper(localName = "consultaFolioFormulario24Response", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", className = "cl.laaraucana.satelites.integracion.ConsultaFolioFormulario24.ConsultaFolioFormulario24Response")
    @Action(input = "http://delegate.toAS.legados.integracion.laaraucana.cl/ConsultaFolioFormulario24/consultaFolioFormulario24Request", output = "http://delegate.toAS.legados.integracion.laaraucana.cl/ConsultaFolioFormulario24/consultaFolioFormulario24Response")
    public ConsultaFolioFormulario24SalidaVO consultaFolioFormulario24(
        @WebParam(name = "arg0", targetNamespace = "")
        ConsultaFolioFormulario24EntradaVO arg0);

}
