//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.satelites.integracion.ConsultaFolioFormulario24;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consultaFolioFormulario24SalidaVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consultaFolioFormulario24SalidaVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fechaOriginacionDeCredito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="folioFormulario24" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="log" type="{http://delegate.toAS.legados.integracion.laaraucana.cl/}log" minOccurs="0"/>
 *         &lt;element name="resultCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultaFolioFormulario24SalidaVO", propOrder = {
    "fechaOriginacionDeCredito",
    "folioFormulario24",
    "log",
    "resultCode"
})
public class ConsultaFolioFormulario24SalidaVO {

    protected String fechaOriginacionDeCredito;
    protected String folioFormulario24;
    protected Log log;
    protected String resultCode;

    /**
     * Gets the value of the fechaOriginacionDeCredito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaOriginacionDeCredito() {
        return fechaOriginacionDeCredito;
    }

    /**
     * Sets the value of the fechaOriginacionDeCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaOriginacionDeCredito(String value) {
        this.fechaOriginacionDeCredito = value;
    }

    /**
     * Gets the value of the folioFormulario24 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolioFormulario24() {
        return folioFormulario24;
    }

    /**
     * Sets the value of the folioFormulario24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolioFormulario24(String value) {
        this.folioFormulario24 = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link Log }
     *     
     */
    public Log getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link Log }
     *     
     */
    public void setLog(Log value) {
        this.log = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

}
