//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.satelites.integracion.ConsultaFolioFormulario24;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ConsultaFolioFormulario24Service", targetNamespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", wsdlLocation = "WEB-INF/wsdl/ConsultaFolioFormulario24.wsdl")
public class ConsultaFolioFormulario24Service
    extends Service
{

    private final static URL CONSULTAFOLIOFORMULARIO24SERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTAFOLIOFORMULARIO24SERVICE_EXCEPTION;
    private final static QName CONSULTAFOLIOFORMULARIO24SERVICE_QNAME = new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "ConsultaFolioFormulario24Service");

    static {
            CONSULTAFOLIOFORMULARIO24SERVICE_WSDL_LOCATION = cl.laaraucana.satelites.integracion.ConsultaFolioFormulario24.ConsultaFolioFormulario24Service.class.getResource("/WEB-INF/wsdl/ConsultaFolioFormulario24.wsdl");
        WebServiceException e = null;
        if (CONSULTAFOLIOFORMULARIO24SERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/ConsultaFolioFormulario24.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSULTAFOLIOFORMULARIO24SERVICE_EXCEPTION = e;
    }

    public ConsultaFolioFormulario24Service() {
        super(__getWsdlLocation(), CONSULTAFOLIOFORMULARIO24SERVICE_QNAME);
    }

    public ConsultaFolioFormulario24Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAFOLIOFORMULARIO24SERVICE_QNAME, features);
    }

    public ConsultaFolioFormulario24Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAFOLIOFORMULARIO24SERVICE_QNAME);
    }

    public ConsultaFolioFormulario24Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAFOLIOFORMULARIO24SERVICE_QNAME, features);
    }

    public ConsultaFolioFormulario24Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaFolioFormulario24Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaFolioFormulario24
     */
    @WebEndpoint(name = "ConsultaFolioFormulario24Port")
    public ConsultaFolioFormulario24 getConsultaFolioFormulario24Port() {
        return super.getPort(new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "ConsultaFolioFormulario24Port"), ConsultaFolioFormulario24.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaFolioFormulario24
     */
    @WebEndpoint(name = "ConsultaFolioFormulario24Port")
    public ConsultaFolioFormulario24 getConsultaFolioFormulario24Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "ConsultaFolioFormulario24Port"), ConsultaFolioFormulario24.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAFOLIOFORMULARIO24SERVICE_EXCEPTION!= null) {
            throw CONSULTAFOLIOFORMULARIO24SERVICE_EXCEPTION;
        }
        return CONSULTAFOLIOFORMULARIO24SERVICE_WSDL_LOCATION;
    }

}
