//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.wssinacofi.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "validaNumeroSerie", namespace = "http://servicios.laaraucana.cl/validaNumeroSerie")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validaNumeroSerie", namespace = "http://servicios.laaraucana.cl/validaNumeroSerie", propOrder = {
    "credenciales",
    "cedula"
})
public class ValidaNumeroSerie {

    @XmlElement(name = "credenciales", namespace = "", required = true)
    private cl.laaraucana.wssinacofi.ws.CredencialesWS credenciales;
    @XmlElement(name = "cedula", namespace = "", required = true)
    private cl.laaraucana.wssinacofi.ws.RequestWS cedula;

    /**
     * 
     * @return
     *     returns CredencialesWS
     */
    public cl.laaraucana.wssinacofi.ws.CredencialesWS getCredenciales() {
        return this.credenciales;
    }

    /**
     * 
     * @param credenciales
     *     the value for the credenciales property
     */
    public void setCredenciales(cl.laaraucana.wssinacofi.ws.CredencialesWS credenciales) {
        this.credenciales = credenciales;
    }

    /**
     * 
     * @return
     *     returns RequestWS
     */
    public cl.laaraucana.wssinacofi.ws.RequestWS getCedula() {
        return this.cedula;
    }

    /**
     * 
     * @param cedula
     *     the value for the cedula property
     */
    public void setCedula(cl.laaraucana.wssinacofi.ws.RequestWS cedula) {
        this.cedula = cedula;
    }

}
