//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.capaservicios.webservices.autogenerado.SolSMS;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "WS_SMS", targetNamespace = "http:mobile.asicom.cl", wsdlLocation = "WEB-INF/wsdl/smsservice.wsdl")
public class WSSMS
    extends Service
{

    private final static URL WSSMS_WSDL_LOCATION;
    private final static WebServiceException WSSMS_EXCEPTION;
    private final static QName WSSMS_QNAME = new QName("http:mobile.asicom.cl", "WS_SMS");

    static {
            WSSMS_WSDL_LOCATION = cl.laaraucana.capaservicios.webservices.autogenerado.SolSMS.WSSMS.class.getResource("/WEB-INF/wsdl/smsservice.wsdl");
        WebServiceException e = null;
        if (WSSMS_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/smsservice.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSSMS_EXCEPTION = e;
    }

    public WSSMS() {
        super(__getWsdlLocation(), WSSMS_QNAME);
    }

    public WSSMS(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSMS_QNAME, features);
    }

    public WSSMS(URL wsdlLocation) {
        super(wsdlLocation, WSSMS_QNAME);
    }

    public WSSMS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSMS_QNAME, features);
    }

    public WSSMS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSSMS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SMSServicePortType
     */
    @WebEndpoint(name = "SMSServicePort")
    public SMSServicePortType getSMSServicePort() {
        return super.getPort(new QName("http:mobile.asicom.cl", "SMSServicePort"), SMSServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMSServicePortType
     */
    @WebEndpoint(name = "SMSServicePort")
    public SMSServicePortType getSMSServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http:mobile.asicom.cl", "SMSServicePort"), SMSServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSMS_EXCEPTION!= null) {
            throw WSSMS_EXCEPTION;
        }
        return WSSMS_WSDL_LOCATION;
    }

}
