//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.mandato.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "ingresarMandatoResponse", namespace = "http://servicio.laaraucana.cl/mandato")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ingresarMandatoResponse", namespace = "http://servicio.laaraucana.cl/mandato")
public class IngresarMandatoResponse {

    @XmlElement(name = "return", namespace = "")
    private cl.laaraucana.transferencias.banco.vo.MandatoResponseWSVO _return;

    /**
     * 
     * @return
     *     returns MandatoResponseWSVO
     */
    public cl.laaraucana.transferencias.banco.vo.MandatoResponseWSVO getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(cl.laaraucana.transferencias.banco.vo.MandatoResponseWSVO _return) {
        this._return = _return;
    }

}
