//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.ventaremota.model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "setSalida", namespace = "http://model.ventaremota.laaraucana.cl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setSalida", namespace = "http://model.ventaremota.laaraucana.cl/")
public class SetSalida {

    @XmlElement(name = "salida", namespace = "")
    private String salida;

    /**
     * 
     * @return
     *     returns String
     */
    public String getSalida() {
        return this.salida;
    }

    /**
     * 
     * @param salida
     *     the value for the salida property
     */
    public void setSalida(String salida) {
        this.salida = salida;
    }

}
