//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.satelites.integracion.ConsultaDatosPagosCreditosPorFolioAs400;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for detalleConsultaDatosPagosCreditosPorFolioAs400SalidaVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="detalleConsultaDatosPagosCreditosPorFolioAs400SalidaVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="estadoAlPago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaUltimoPago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="glosaEstadoPago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="montoTotalAbonadoACuota" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroCuota" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroDocUltimoPago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="oficinaUltimoPago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoDocUltimoPago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "detalleConsultaDatosPagosCreditosPorFolioAs400SalidaVO", propOrder = {
    "estadoAlPago",
    "fechaUltimoPago",
    "fechaVencimiento",
    "glosaEstadoPago",
    "montoTotalAbonadoACuota",
    "numeroCuota",
    "numeroDocUltimoPago",
    "oficinaUltimoPago",
    "tipoDocUltimoPago"
})
public class DetalleConsultaDatosPagosCreditosPorFolioAs400SalidaVO {

    protected String estadoAlPago;
    protected String fechaUltimoPago;
    protected String fechaVencimiento;
    protected String glosaEstadoPago;
    protected String montoTotalAbonadoACuota;
    protected String numeroCuota;
    protected String numeroDocUltimoPago;
    protected String oficinaUltimoPago;
    protected String tipoDocUltimoPago;

    /**
     * Gets the value of the estadoAlPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoAlPago() {
        return estadoAlPago;
    }

    /**
     * Sets the value of the estadoAlPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoAlPago(String value) {
        this.estadoAlPago = value;
    }

    /**
     * Gets the value of the fechaUltimoPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaUltimoPago() {
        return fechaUltimoPago;
    }

    /**
     * Sets the value of the fechaUltimoPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaUltimoPago(String value) {
        this.fechaUltimoPago = value;
    }

    /**
     * Gets the value of the fechaVencimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaVencimiento() {
        return fechaVencimiento;
    }

    /**
     * Sets the value of the fechaVencimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaVencimiento(String value) {
        this.fechaVencimiento = value;
    }

    /**
     * Gets the value of the glosaEstadoPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlosaEstadoPago() {
        return glosaEstadoPago;
    }

    /**
     * Sets the value of the glosaEstadoPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlosaEstadoPago(String value) {
        this.glosaEstadoPago = value;
    }

    /**
     * Gets the value of the montoTotalAbonadoACuota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMontoTotalAbonadoACuota() {
        return montoTotalAbonadoACuota;
    }

    /**
     * Sets the value of the montoTotalAbonadoACuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMontoTotalAbonadoACuota(String value) {
        this.montoTotalAbonadoACuota = value;
    }

    /**
     * Gets the value of the numeroCuota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroCuota() {
        return numeroCuota;
    }

    /**
     * Sets the value of the numeroCuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroCuota(String value) {
        this.numeroCuota = value;
    }

    /**
     * Gets the value of the numeroDocUltimoPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroDocUltimoPago() {
        return numeroDocUltimoPago;
    }

    /**
     * Sets the value of the numeroDocUltimoPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroDocUltimoPago(String value) {
        this.numeroDocUltimoPago = value;
    }

    /**
     * Gets the value of the oficinaUltimoPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOficinaUltimoPago() {
        return oficinaUltimoPago;
    }

    /**
     * Sets the value of the oficinaUltimoPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOficinaUltimoPago(String value) {
        this.oficinaUltimoPago = value;
    }

    /**
     * Gets the value of the tipoDocUltimoPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocUltimoPago() {
        return tipoDocUltimoPago;
    }

    /**
     * Sets the value of the tipoDocUltimoPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocUltimoPago(String value) {
        this.tipoDocUltimoPago = value;
    }

}
