//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CTEstado complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTEstado">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="estado_licencia" type="{urn:www:lme:gov:cl:lme}STEstado_licencia"/>
 *         &lt;element name="fecha_estado" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *       &lt;attribute name="motivo_norecepcion" type="{urn:www:lme:gov:cl:lme}STMotivo_norecepcion" />
 *       &lt;attribute name="fecha_termino_relacion" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="emp_rut" type="{urn:www:lme:gov:cl:lme}STRut" />
 *       &lt;attribute name="codigo_tramitacion_CCAF" type="{urn:www:lme:gov:cl:lme}STCodigoCCAF" />
 *       &lt;attribute name="motivo_devolucion_CCAF" type="{urn:www:lme:gov:cl:lme}STMotivo_devolucionCCAF" />
 *       &lt;attribute name="motivo_devolucion_CCAF_otro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tipo_liquidacion_CCAF" type="{urn:www:lme:gov:cl:lme}STTipo_liquidacionCCAF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTEstado", propOrder = {
    "estadoLicencia",
    "fechaEstado"
})
public class CTEstado {

    @XmlElement(name = "estado_licencia", required = true)
    protected BigInteger estadoLicencia;
    @XmlElement(name = "fecha_estado", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaEstado;
    @XmlAttribute(name = "motivo_norecepcion")
    protected BigInteger motivoNorecepcion;
    @XmlAttribute(name = "fecha_termino_relacion")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaTerminoRelacion;
    @XmlAttribute(name = "emp_rut")
    protected String empRut;
    @XmlAttribute(name = "codigo_tramitacion_CCAF")
    protected BigInteger codigoTramitacionCCAF;
    @XmlAttribute(name = "motivo_devolucion_CCAF")
    protected BigInteger motivoDevolucionCCAF;
    @XmlAttribute(name = "motivo_devolucion_CCAF_otro")
    protected String motivoDevolucionCCAFOtro;
    @XmlAttribute(name = "tipo_liquidacion_CCAF")
    protected BigInteger tipoLiquidacionCCAF;

    /**
     * Gets the value of the estadoLicencia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEstadoLicencia() {
        return estadoLicencia;
    }

    /**
     * Sets the value of the estadoLicencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEstadoLicencia(BigInteger value) {
        this.estadoLicencia = value;
    }

    /**
     * Gets the value of the fechaEstado property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEstado() {
        return fechaEstado;
    }

    /**
     * Sets the value of the fechaEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaEstado(XMLGregorianCalendar value) {
        this.fechaEstado = value;
    }

    /**
     * Gets the value of the motivoNorecepcion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMotivoNorecepcion() {
        return motivoNorecepcion;
    }

    /**
     * Sets the value of the motivoNorecepcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMotivoNorecepcion(BigInteger value) {
        this.motivoNorecepcion = value;
    }

    /**
     * Gets the value of the fechaTerminoRelacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaTerminoRelacion() {
        return fechaTerminoRelacion;
    }

    /**
     * Sets the value of the fechaTerminoRelacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaTerminoRelacion(XMLGregorianCalendar value) {
        this.fechaTerminoRelacion = value;
    }

    /**
     * Gets the value of the empRut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpRut() {
        return empRut;
    }

    /**
     * Sets the value of the empRut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpRut(String value) {
        this.empRut = value;
    }

    /**
     * Gets the value of the codigoTramitacionCCAF property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoTramitacionCCAF() {
        return codigoTramitacionCCAF;
    }

    /**
     * Sets the value of the codigoTramitacionCCAF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoTramitacionCCAF(BigInteger value) {
        this.codigoTramitacionCCAF = value;
    }

    /**
     * Gets the value of the motivoDevolucionCCAF property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMotivoDevolucionCCAF() {
        return motivoDevolucionCCAF;
    }

    /**
     * Sets the value of the motivoDevolucionCCAF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMotivoDevolucionCCAF(BigInteger value) {
        this.motivoDevolucionCCAF = value;
    }

    /**
     * Gets the value of the motivoDevolucionCCAFOtro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotivoDevolucionCCAFOtro() {
        return motivoDevolucionCCAFOtro;
    }

    /**
     * Sets the value of the motivoDevolucionCCAFOtro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotivoDevolucionCCAFOtro(String value) {
        this.motivoDevolucionCCAFOtro = value;
    }

    /**
     * Gets the value of the tipoLiquidacionCCAF property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTipoLiquidacionCCAF() {
        return tipoLiquidacionCCAF;
    }

    /**
     * Sets the value of the tipoLiquidacionCCAF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTipoLiquidacionCCAF(BigInteger value) {
        this.tipoLiquidacionCCAF = value;
    }

}
