//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CTHaberes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTHaberes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="detalle" type="{urn:www:lme:gov:cl:lme}CTDetalleHaber" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="archivo" type="{urn:www:lme:gov:cl:lme}CTDireccion_archivo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTHaberes", propOrder = {
    "detalle",
    "archivo"
})
public class CTHaberes {

    protected List<CTDetalleHaber> detalle;
    protected List<CTDireccionArchivo> archivo;

    /**
     * Gets the value of the detalle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detalle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetalle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTDetalleHaber }
     * 
     * 
     */
    public List<CTDetalleHaber> getDetalle() {
        if (detalle == null) {
            detalle = new ArrayList<CTDetalleHaber>();
        }
        return this.detalle;
    }

    /**
     * Gets the value of the archivo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the archivo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchivo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTDireccionArchivo }
     * 
     * 
     */
    public List<CTDireccionArchivo> getArchivo() {
        if (archivo == null) {
            archivo = new ArrayList<CTDireccionArchivo>();
        }
        return this.archivo;
    }

}
