//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Una huella digital, incluye:
 *         - El RUT de la persona que firma (informativo, se puede inferir de la huella).
 *         - La huella digital en formato WSQ y codificada en "Base 64".
 *         - El hash de la parte del documento que se esta firmando.
 *       
 * 
 * <p>Java class for CTHuellaDigital complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTHuellaDigital">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rut" type="{urn:www:lme:gov:cl:lme}STRut"/>
 *         &lt;element name="huella" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="hash" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTHuellaDigital", propOrder = {
    "rut",
    "huella",
    "hash"
})
public class CTHuellaDigital {

    @XmlElement(required = true)
    protected String rut;
    @XmlElement(required = true)
    protected byte[] huella;
    @XmlElement(required = true)
    protected byte[] hash;

    /**
     * Gets the value of the rut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRut() {
        return rut;
    }

    /**
     * Sets the value of the rut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRut(String value) {
        this.rut = value;
    }

    /**
     * Gets the value of the huella property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getHuella() {
        return huella;
    }

    /**
     * Sets the value of the huella property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setHuella(byte[] value) {
        this.huella = ((byte[]) value);
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setHash(byte[] value) {
        this.hash = ((byte[]) value);
    }

}
