//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CTLiquidacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTLiquidacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="periodo_renta" type="{http://www.w3.org/2001/XMLSchema}gYearMonth"/>
 *         &lt;element name="monto_subsidio_diario" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="monto_aporte_pensiones" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="monto_aporte_salud" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="monto_seguro_Cesantia" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="monto_apagar_subsidio" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="fecha_desde_liquidacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="fecha_hasta_liquidacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="fecha_pago_probable" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ndias_apagar_subsidios" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ndias_apagar_prevision" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tipo_liquidacion_CCAF" type="{urn:www:lme:gov:cl:lme}STTipo_liquidacionCCAF" />
 *       &lt;attribute name="evento_liquidacion_CCAF" type="{urn:www:lme:gov:cl:lme}STEvento_liquidacionCCAF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTLiquidacion", propOrder = {
    "periodoRenta",
    "montoSubsidioDiario",
    "montoAportePensiones",
    "montoAporteSalud",
    "montoSeguroCesantia",
    "montoApagarSubsidio",
    "fechaDesdeLiquidacion",
    "fechaHastaLiquidacion",
    "fechaPagoProbable",
    "ndiasApagarSubsidios",
    "ndiasApagarPrevision"
})
public class CTLiquidacion {

    @XmlElement(name = "periodo_renta", required = true)
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar periodoRenta;
    @XmlElement(name = "monto_subsidio_diario")
    protected BigInteger montoSubsidioDiario;
    @XmlElement(name = "monto_aporte_pensiones")
    protected BigInteger montoAportePensiones;
    @XmlElement(name = "monto_aporte_salud")
    protected BigInteger montoAporteSalud;
    @XmlElement(name = "monto_seguro_Cesantia")
    protected BigInteger montoSeguroCesantia;
    @XmlElement(name = "monto_apagar_subsidio")
    protected BigInteger montoApagarSubsidio;
    @XmlElement(name = "fecha_desde_liquidacion")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaDesdeLiquidacion;
    @XmlElement(name = "fecha_hasta_liquidacion")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaHastaLiquidacion;
    @XmlElement(name = "fecha_pago_probable")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaPagoProbable;
    @XmlElement(name = "ndias_apagar_subsidios")
    protected BigInteger ndiasApagarSubsidios;
    @XmlElement(name = "ndias_apagar_prevision")
    protected BigInteger ndiasApagarPrevision;
    @XmlAttribute(name = "tipo_liquidacion_CCAF")
    protected BigInteger tipoLiquidacionCCAF;
    @XmlAttribute(name = "evento_liquidacion_CCAF")
    protected BigInteger eventoLiquidacionCCAF;

    /**
     * Gets the value of the periodoRenta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodoRenta() {
        return periodoRenta;
    }

    /**
     * Sets the value of the periodoRenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodoRenta(XMLGregorianCalendar value) {
        this.periodoRenta = value;
    }

    /**
     * Gets the value of the montoSubsidioDiario property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMontoSubsidioDiario() {
        return montoSubsidioDiario;
    }

    /**
     * Sets the value of the montoSubsidioDiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMontoSubsidioDiario(BigInteger value) {
        this.montoSubsidioDiario = value;
    }

    /**
     * Gets the value of the montoAportePensiones property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMontoAportePensiones() {
        return montoAportePensiones;
    }

    /**
     * Sets the value of the montoAportePensiones property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMontoAportePensiones(BigInteger value) {
        this.montoAportePensiones = value;
    }

    /**
     * Gets the value of the montoAporteSalud property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMontoAporteSalud() {
        return montoAporteSalud;
    }

    /**
     * Sets the value of the montoAporteSalud property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMontoAporteSalud(BigInteger value) {
        this.montoAporteSalud = value;
    }

    /**
     * Gets the value of the montoSeguroCesantia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMontoSeguroCesantia() {
        return montoSeguroCesantia;
    }

    /**
     * Sets the value of the montoSeguroCesantia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMontoSeguroCesantia(BigInteger value) {
        this.montoSeguroCesantia = value;
    }

    /**
     * Gets the value of the montoApagarSubsidio property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMontoApagarSubsidio() {
        return montoApagarSubsidio;
    }

    /**
     * Sets the value of the montoApagarSubsidio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMontoApagarSubsidio(BigInteger value) {
        this.montoApagarSubsidio = value;
    }

    /**
     * Gets the value of the fechaDesdeLiquidacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaDesdeLiquidacion() {
        return fechaDesdeLiquidacion;
    }

    /**
     * Sets the value of the fechaDesdeLiquidacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaDesdeLiquidacion(XMLGregorianCalendar value) {
        this.fechaDesdeLiquidacion = value;
    }

    /**
     * Gets the value of the fechaHastaLiquidacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaHastaLiquidacion() {
        return fechaHastaLiquidacion;
    }

    /**
     * Sets the value of the fechaHastaLiquidacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaHastaLiquidacion(XMLGregorianCalendar value) {
        this.fechaHastaLiquidacion = value;
    }

    /**
     * Gets the value of the fechaPagoProbable property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaPagoProbable() {
        return fechaPagoProbable;
    }

    /**
     * Sets the value of the fechaPagoProbable property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaPagoProbable(XMLGregorianCalendar value) {
        this.fechaPagoProbable = value;
    }

    /**
     * Gets the value of the ndiasApagarSubsidios property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNdiasApagarSubsidios() {
        return ndiasApagarSubsidios;
    }

    /**
     * Sets the value of the ndiasApagarSubsidios property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNdiasApagarSubsidios(BigInteger value) {
        this.ndiasApagarSubsidios = value;
    }

    /**
     * Gets the value of the ndiasApagarPrevision property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNdiasApagarPrevision() {
        return ndiasApagarPrevision;
    }

    /**
     * Sets the value of the ndiasApagarPrevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNdiasApagarPrevision(BigInteger value) {
        this.ndiasApagarPrevision = value;
    }

    /**
     * Gets the value of the tipoLiquidacionCCAF property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTipoLiquidacionCCAF() {
        return tipoLiquidacionCCAF;
    }

    /**
     * Sets the value of the tipoLiquidacionCCAF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTipoLiquidacionCCAF(BigInteger value) {
        this.tipoLiquidacionCCAF = value;
    }

    /**
     * Gets the value of the eventoLiquidacionCCAF property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEventoLiquidacionCCAF() {
        return eventoLiquidacionCCAF;
    }

    /**
     * Sets the value of the eventoLiquidacionCCAF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEventoLiquidacionCCAF(BigInteger value) {
        this.eventoLiquidacionCCAF = value;
    }

}
