//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CTPrestador complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTPrestador">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipo_prestador" type="{urn:www:lme:gov:cl:lme}STTipo_prestador"/>
 *         &lt;element name="rut_prestador" type="{urn:www:lme:gov:cl:lme}STRut"/>
 *         &lt;element name="codigo_publico" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="codigo_interno_operador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTPrestador", propOrder = {
    "tipoPrestador",
    "rutPrestador",
    "codigoPublico",
    "codigoInternoOperador"
})
public class CTPrestador {

    @XmlElement(name = "tipo_prestador", required = true)
    protected BigInteger tipoPrestador;
    @XmlElement(name = "rut_prestador", required = true)
    protected String rutPrestador;
    @XmlElement(name = "codigo_publico")
    protected String codigoPublico;
    @XmlElement(name = "codigo_interno_operador", required = true)
    protected String codigoInternoOperador;

    /**
     * Gets the value of the tipoPrestador property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTipoPrestador() {
        return tipoPrestador;
    }

    /**
     * Sets the value of the tipoPrestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTipoPrestador(BigInteger value) {
        this.tipoPrestador = value;
    }

    /**
     * Gets the value of the rutPrestador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRutPrestador() {
        return rutPrestador;
    }

    /**
     * Sets the value of the rutPrestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRutPrestador(String value) {
        this.rutPrestador = value;
    }

    /**
     * Gets the value of the codigoPublico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoPublico() {
        return codigoPublico;
    }

    /**
     * Sets the value of the codigoPublico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoPublico(String value) {
        this.codigoPublico = value;
    }

    /**
     * Gets the value of the codigoInternoOperador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoInternoOperador() {
        return codigoInternoOperador;
    }

    /**
     * Sets the value of the codigoInternoOperador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoInternoOperador(String value) {
        this.codigoInternoOperador = value;
    }

}
