//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CT_resolucion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_resolucion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="n_resolucion" type="{urn:www:lme:gov:cl:lme}STN_resolucion"/>
 *         &lt;element name="establecimiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigo_establecimiento" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="codigo_tipo_licencia_entidad" type="{urn:www:lme:gov:cl:lme}STTipo_licencia"/>
 *         &lt;element name="entidad_fecha_desde" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="entidad_fecha_hasta" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="entidad_ndias" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="codigo_diagnostico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigo_continuacion" type="{urn:www:lme:gov:cl:lme}STContinuacion"/>
 *         &lt;element name="dias_previos" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="codigo_tipo_resolucion" type="{urn:www:lme:gov:cl:lme}STTipo_resolucion"/>
 *         &lt;element name="entidad_pendiente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="codigo_redictamen" type="{urn:www:lme:gov:cl:lme}STSiNo" minOccurs="0"/>
 *         &lt;element name="codigo_causa_rechazo" type="{urn:www:lme:gov:cl:lme}STCausa_rechazo" minOccurs="0"/>
 *         &lt;element name="entidad_causa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="codigo_reposo_autorizado" type="{urn:www:lme:gov:cl:lme}STTipo_reposo"/>
 *         &lt;element name="codigo_jornada_reposo_autorizado" type="{urn:www:lme:gov:cl:lme}STJornada_reposo" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="codigo_derecho_subsidio" type="{urn:www:lme:gov:cl:lme}STTipo_subsidio"/>
 *         &lt;element name="entidad_fecha_recepcion" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="fecha_resolucion" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="fecha_redictamen" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="contralor_nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contralor_rut" type="{urn:www:lme:gov:cl:lme}STRut"/>
 *         &lt;element name="contralor_registro_colegio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tipo_pronunciamiento" use="required" type="{urn:www:lme:gov:cl:lme}STTipo_pronunciamiento" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="tipo_pendiente" type="{urn:www:lme:gov:cl:lme}STTipo_pendiente" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_resolucion", propOrder = {
    "entidad",
    "nResolucion",
    "establecimiento",
    "codigoEstablecimiento",
    "codigoTipoLicenciaEntidad",
    "entidadFechaDesde",
    "entidadFechaHasta",
    "entidadNdias",
    "codigoDiagnostico",
    "codigoContinuacion",
    "diasPrevios",
    "codigoTipoResolucion",
    "entidadPendiente",
    "codigoRedictamen",
    "codigoCausaRechazo",
    "entidadCausa",
    "codigoReposoAutorizado",
    "codigoJornadaReposoAutorizado",
    "codigoDerechoSubsidio",
    "entidadFechaRecepcion",
    "fechaResolucion",
    "fechaRedictamen",
    "contralorNombre",
    "contralorRut",
    "contralorRegistroColegio"
})
public class CTResolucion {

    @XmlElement(required = true)
    protected String entidad;
    @XmlElement(name = "n_resolucion", required = true)
    protected String nResolucion;
    @XmlElement(required = true)
    protected String establecimiento;
    @XmlElement(name = "codigo_establecimiento", required = true)
    protected BigInteger codigoEstablecimiento;
    @XmlElement(name = "codigo_tipo_licencia_entidad", required = true)
    protected BigInteger codigoTipoLicenciaEntidad;
    @XmlElement(name = "entidad_fecha_desde", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar entidadFechaDesde;
    @XmlElement(name = "entidad_fecha_hasta", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar entidadFechaHasta;
    @XmlElement(name = "entidad_ndias", required = true)
    protected BigInteger entidadNdias;
    @XmlElement(name = "codigo_diagnostico", required = true)
    protected String codigoDiagnostico;
    @XmlElement(name = "codigo_continuacion", required = true)
    protected BigInteger codigoContinuacion;
    @XmlElement(name = "dias_previos")
    protected BigInteger diasPrevios;
    @XmlElement(name = "codigo_tipo_resolucion", required = true)
    protected BigInteger codigoTipoResolucion;
    @XmlElement(name = "entidad_pendiente")
    protected String entidadPendiente;
    @XmlElement(name = "codigo_redictamen")
    protected BigInteger codigoRedictamen;
    @XmlElement(name = "codigo_causa_rechazo")
    protected BigInteger codigoCausaRechazo;
    @XmlElement(name = "entidad_causa")
    protected String entidadCausa;
    @XmlElement(name = "codigo_reposo_autorizado", required = true)
    protected BigInteger codigoReposoAutorizado;
    @XmlElement(name = "codigo_jornada_reposo_autorizado")
    protected List<STJornadaReposo> codigoJornadaReposoAutorizado;
    @XmlElement(name = "codigo_derecho_subsidio", required = true)
    protected STTipoSubsidio codigoDerechoSubsidio;
    @XmlElement(name = "entidad_fecha_recepcion", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar entidadFechaRecepcion;
    @XmlElement(name = "fecha_resolucion", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaResolucion;
    @XmlElement(name = "fecha_redictamen")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaRedictamen;
    @XmlElement(name = "contralor_nombre", required = true)
    protected String contralorNombre;
    @XmlElement(name = "contralor_rut", required = true)
    protected String contralorRut;
    @XmlElement(name = "contralor_registro_colegio")
    protected String contralorRegistroColegio;
    @XmlAttribute(name = "tipo_pronunciamiento", required = true)
    protected BigInteger tipoPronunciamiento;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "tipo_pendiente")
    protected BigInteger tipoPendiente;

    /**
     * Gets the value of the entidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidad() {
        return entidad;
    }

    /**
     * Sets the value of the entidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidad(String value) {
        this.entidad = value;
    }

    /**
     * Gets the value of the nResolucion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNResolucion() {
        return nResolucion;
    }

    /**
     * Sets the value of the nResolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNResolucion(String value) {
        this.nResolucion = value;
    }

    /**
     * Gets the value of the establecimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstablecimiento() {
        return establecimiento;
    }

    /**
     * Sets the value of the establecimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstablecimiento(String value) {
        this.establecimiento = value;
    }

    /**
     * Gets the value of the codigoEstablecimiento property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoEstablecimiento() {
        return codigoEstablecimiento;
    }

    /**
     * Sets the value of the codigoEstablecimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoEstablecimiento(BigInteger value) {
        this.codigoEstablecimiento = value;
    }

    /**
     * Gets the value of the codigoTipoLicenciaEntidad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoTipoLicenciaEntidad() {
        return codigoTipoLicenciaEntidad;
    }

    /**
     * Sets the value of the codigoTipoLicenciaEntidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoTipoLicenciaEntidad(BigInteger value) {
        this.codigoTipoLicenciaEntidad = value;
    }

    /**
     * Gets the value of the entidadFechaDesde property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntidadFechaDesde() {
        return entidadFechaDesde;
    }

    /**
     * Sets the value of the entidadFechaDesde property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntidadFechaDesde(XMLGregorianCalendar value) {
        this.entidadFechaDesde = value;
    }

    /**
     * Gets the value of the entidadFechaHasta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntidadFechaHasta() {
        return entidadFechaHasta;
    }

    /**
     * Sets the value of the entidadFechaHasta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntidadFechaHasta(XMLGregorianCalendar value) {
        this.entidadFechaHasta = value;
    }

    /**
     * Gets the value of the entidadNdias property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEntidadNdias() {
        return entidadNdias;
    }

    /**
     * Sets the value of the entidadNdias property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEntidadNdias(BigInteger value) {
        this.entidadNdias = value;
    }

    /**
     * Gets the value of the codigoDiagnostico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoDiagnostico() {
        return codigoDiagnostico;
    }

    /**
     * Sets the value of the codigoDiagnostico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoDiagnostico(String value) {
        this.codigoDiagnostico = value;
    }

    /**
     * Gets the value of the codigoContinuacion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoContinuacion() {
        return codigoContinuacion;
    }

    /**
     * Sets the value of the codigoContinuacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoContinuacion(BigInteger value) {
        this.codigoContinuacion = value;
    }

    /**
     * Gets the value of the diasPrevios property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDiasPrevios() {
        return diasPrevios;
    }

    /**
     * Sets the value of the diasPrevios property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDiasPrevios(BigInteger value) {
        this.diasPrevios = value;
    }

    /**
     * Gets the value of the codigoTipoResolucion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoTipoResolucion() {
        return codigoTipoResolucion;
    }

    /**
     * Sets the value of the codigoTipoResolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoTipoResolucion(BigInteger value) {
        this.codigoTipoResolucion = value;
    }

    /**
     * Gets the value of the entidadPendiente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidadPendiente() {
        return entidadPendiente;
    }

    /**
     * Sets the value of the entidadPendiente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidadPendiente(String value) {
        this.entidadPendiente = value;
    }

    /**
     * Gets the value of the codigoRedictamen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoRedictamen() {
        return codigoRedictamen;
    }

    /**
     * Sets the value of the codigoRedictamen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoRedictamen(BigInteger value) {
        this.codigoRedictamen = value;
    }

    /**
     * Gets the value of the codigoCausaRechazo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoCausaRechazo() {
        return codigoCausaRechazo;
    }

    /**
     * Sets the value of the codigoCausaRechazo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoCausaRechazo(BigInteger value) {
        this.codigoCausaRechazo = value;
    }

    /**
     * Gets the value of the entidadCausa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidadCausa() {
        return entidadCausa;
    }

    /**
     * Sets the value of the entidadCausa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidadCausa(String value) {
        this.entidadCausa = value;
    }

    /**
     * Gets the value of the codigoReposoAutorizado property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoReposoAutorizado() {
        return codigoReposoAutorizado;
    }

    /**
     * Sets the value of the codigoReposoAutorizado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoReposoAutorizado(BigInteger value) {
        this.codigoReposoAutorizado = value;
    }

    /**
     * Gets the value of the codigoJornadaReposoAutorizado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codigoJornadaReposoAutorizado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodigoJornadaReposoAutorizado().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STJornadaReposo }
     * 
     * 
     */
    public List<STJornadaReposo> getCodigoJornadaReposoAutorizado() {
        if (codigoJornadaReposoAutorizado == null) {
            codigoJornadaReposoAutorizado = new ArrayList<STJornadaReposo>();
        }
        return this.codigoJornadaReposoAutorizado;
    }

    /**
     * Gets the value of the codigoDerechoSubsidio property.
     * 
     * @return
     *     possible object is
     *     {@link STTipoSubsidio }
     *     
     */
    public STTipoSubsidio getCodigoDerechoSubsidio() {
        return codigoDerechoSubsidio;
    }

    /**
     * Sets the value of the codigoDerechoSubsidio property.
     * 
     * @param value
     *     allowed object is
     *     {@link STTipoSubsidio }
     *     
     */
    public void setCodigoDerechoSubsidio(STTipoSubsidio value) {
        this.codigoDerechoSubsidio = value;
    }

    /**
     * Gets the value of the entidadFechaRecepcion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntidadFechaRecepcion() {
        return entidadFechaRecepcion;
    }

    /**
     * Sets the value of the entidadFechaRecepcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntidadFechaRecepcion(XMLGregorianCalendar value) {
        this.entidadFechaRecepcion = value;
    }

    /**
     * Gets the value of the fechaResolucion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaResolucion() {
        return fechaResolucion;
    }

    /**
     * Sets the value of the fechaResolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaResolucion(XMLGregorianCalendar value) {
        this.fechaResolucion = value;
    }

    /**
     * Gets the value of the fechaRedictamen property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaRedictamen() {
        return fechaRedictamen;
    }

    /**
     * Sets the value of the fechaRedictamen property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaRedictamen(XMLGregorianCalendar value) {
        this.fechaRedictamen = value;
    }

    /**
     * Gets the value of the contralorNombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContralorNombre() {
        return contralorNombre;
    }

    /**
     * Sets the value of the contralorNombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContralorNombre(String value) {
        this.contralorNombre = value;
    }

    /**
     * Gets the value of the contralorRut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContralorRut() {
        return contralorRut;
    }

    /**
     * Sets the value of the contralorRut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContralorRut(String value) {
        this.contralorRut = value;
    }

    /**
     * Gets the value of the contralorRegistroColegio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContralorRegistroColegio() {
        return contralorRegistroColegio;
    }

    /**
     * Sets the value of the contralorRegistroColegio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContralorRegistroColegio(String value) {
        this.contralorRegistroColegio = value;
    }

    /**
     * Gets the value of the tipoPronunciamiento property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTipoPronunciamiento() {
        return tipoPronunciamiento;
    }

    /**
     * Sets the value of the tipoPronunciamiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTipoPronunciamiento(BigInteger value) {
        this.tipoPronunciamiento = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the tipoPendiente property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTipoPendiente() {
        return tipoPendiente;
    }

    /**
     * Sets the value of the tipoPendiente property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTipoPendiente(BigInteger value) {
        this.tipoPendiente = value;
    }

}
