//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CTRemuneracion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTRemuneracion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigo_prevision_rem_ant" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ano_mes_rem_ant" type="{http://www.w3.org/2001/XMLSchema}gYearMonth"/>
 *         &lt;element name="ndias_rem_ant" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="monto_imponible_rem_ant" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="monto_total_rem_ant" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="monto_incapacidad_rem_ant" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ndias_incapacidad_rem_ant" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTRemuneracion", propOrder = {
    "codigoPrevisionRemAnt",
    "anoMesRemAnt",
    "ndiasRemAnt",
    "montoImponibleRemAnt",
    "montoTotalRemAnt",
    "montoIncapacidadRemAnt",
    "ndiasIncapacidadRemAnt"
})
public class CTRemuneracion {

    @XmlElement(name = "codigo_prevision_rem_ant", required = true)
    protected BigInteger codigoPrevisionRemAnt;
    @XmlElement(name = "ano_mes_rem_ant", required = true)
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar anoMesRemAnt;
    @XmlElement(name = "ndias_rem_ant", required = true)
    protected BigInteger ndiasRemAnt;
    @XmlElement(name = "monto_imponible_rem_ant")
    protected BigInteger montoImponibleRemAnt;
    @XmlElement(name = "monto_total_rem_ant")
    protected BigInteger montoTotalRemAnt;
    @XmlElement(name = "monto_incapacidad_rem_ant")
    protected BigInteger montoIncapacidadRemAnt;
    @XmlElement(name = "ndias_incapacidad_rem_ant")
    protected BigInteger ndiasIncapacidadRemAnt;

    /**
     * Gets the value of the codigoPrevisionRemAnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoPrevisionRemAnt() {
        return codigoPrevisionRemAnt;
    }

    /**
     * Sets the value of the codigoPrevisionRemAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoPrevisionRemAnt(BigInteger value) {
        this.codigoPrevisionRemAnt = value;
    }

    /**
     * Gets the value of the anoMesRemAnt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAnoMesRemAnt() {
        return anoMesRemAnt;
    }

    /**
     * Sets the value of the anoMesRemAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAnoMesRemAnt(XMLGregorianCalendar value) {
        this.anoMesRemAnt = value;
    }

    /**
     * Gets the value of the ndiasRemAnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNdiasRemAnt() {
        return ndiasRemAnt;
    }

    /**
     * Sets the value of the ndiasRemAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNdiasRemAnt(BigInteger value) {
        this.ndiasRemAnt = value;
    }

    /**
     * Gets the value of the montoImponibleRemAnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMontoImponibleRemAnt() {
        return montoImponibleRemAnt;
    }

    /**
     * Sets the value of the montoImponibleRemAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMontoImponibleRemAnt(BigInteger value) {
        this.montoImponibleRemAnt = value;
    }

    /**
     * Gets the value of the montoTotalRemAnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMontoTotalRemAnt() {
        return montoTotalRemAnt;
    }

    /**
     * Sets the value of the montoTotalRemAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMontoTotalRemAnt(BigInteger value) {
        this.montoTotalRemAnt = value;
    }

    /**
     * Gets the value of the montoIncapacidadRemAnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMontoIncapacidadRemAnt() {
        return montoIncapacidadRemAnt;
    }

    /**
     * Sets the value of the montoIncapacidadRemAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMontoIncapacidadRemAnt(BigInteger value) {
        this.montoIncapacidadRemAnt = value;
    }

    /**
     * Gets the value of the ndiasIncapacidadRemAnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNdiasIncapacidadRemAnt() {
        return ndiasIncapacidadRemAnt;
    }

    /**
     * Sets the value of the ndiasIncapacidadRemAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNdiasIncapacidadRemAnt(BigInteger value) {
        this.ndiasIncapacidadRemAnt = value;
    }

}
