//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_ZONA_C3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_ZONA_C3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="remuneracion" type="{urn:www:lme:gov:cl:lme}CTRemuneracion" maxOccurs="12"/>
 *         &lt;element name="porcen_desahucio" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="monto_imponible_mes_anterior" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_ZONA_C3", propOrder = {
    "remuneracion",
    "porcenDesahucio",
    "montoImponibleMesAnterior"
})
public class CTZONAC3 {

    @XmlElement(required = true)
    protected List<CTRemuneracion> remuneracion;
    @XmlElement(name = "porcen_desahucio")
    protected BigDecimal porcenDesahucio;
    @XmlElement(name = "monto_imponible_mes_anterior")
    protected BigInteger montoImponibleMesAnterior;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the remuneracion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remuneracion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemuneracion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTRemuneracion }
     * 
     * 
     */
    public List<CTRemuneracion> getRemuneracion() {
        if (remuneracion == null) {
            remuneracion = new ArrayList<CTRemuneracion>();
        }
        return this.remuneracion;
    }

    /**
     * Gets the value of the porcenDesahucio property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPorcenDesahucio() {
        return porcenDesahucio;
    }

    /**
     * Sets the value of the porcenDesahucio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPorcenDesahucio(BigDecimal value) {
        this.porcenDesahucio = value;
    }

    /**
     * Gets the value of the montoImponibleMesAnterior property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMontoImponibleMesAnterior() {
        return montoImponibleMesAnterior;
    }

    /**
     * Sets the value of the montoImponibleMesAnterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMontoImponibleMesAnterior(BigInteger value) {
        this.montoImponibleMesAnterior = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
