//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CT_ZONA_A3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_ZONA_A3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigo_tipo_licencia" type="{urn:www:lme:gov:cl:lme}STTipo_licencia"/>
 *         &lt;element name="codigo_recuperabilidad" type="{urn:www:lme:gov:cl:lme}STSiNo"/>
 *         &lt;element name="codigo_inicio_tram_inv" type="{urn:www:lme:gov:cl:lme}STSiNo"/>
 *         &lt;element name="fecha_accidente" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="codigo_trayecto" type="{urn:www:lme:gov:cl:lme}STSiNo" minOccurs="0"/>
 *         &lt;element name="fecha_concepcion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_ZONA_A3", propOrder = {
    "codigoTipoLicencia",
    "codigoRecuperabilidad",
    "codigoInicioTramInv",
    "fechaAccidente",
    "codigoTrayecto",
    "fechaConcepcion"
})
public class CTZONAA3 {

    @XmlElement(name = "codigo_tipo_licencia", required = true)
    protected BigInteger codigoTipoLicencia;
    @XmlElement(name = "codigo_recuperabilidad", required = true)
    protected BigInteger codigoRecuperabilidad;
    @XmlElement(name = "codigo_inicio_tram_inv", required = true)
    protected BigInteger codigoInicioTramInv;
    @XmlElement(name = "fecha_accidente")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaAccidente;
    @XmlElement(name = "codigo_trayecto")
    protected BigInteger codigoTrayecto;
    @XmlElement(name = "fecha_concepcion")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaConcepcion;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the codigoTipoLicencia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoTipoLicencia() {
        return codigoTipoLicencia;
    }

    /**
     * Sets the value of the codigoTipoLicencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoTipoLicencia(BigInteger value) {
        this.codigoTipoLicencia = value;
    }

    /**
     * Gets the value of the codigoRecuperabilidad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoRecuperabilidad() {
        return codigoRecuperabilidad;
    }

    /**
     * Sets the value of the codigoRecuperabilidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoRecuperabilidad(BigInteger value) {
        this.codigoRecuperabilidad = value;
    }

    /**
     * Gets the value of the codigoInicioTramInv property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoInicioTramInv() {
        return codigoInicioTramInv;
    }

    /**
     * Sets the value of the codigoInicioTramInv property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoInicioTramInv(BigInteger value) {
        this.codigoInicioTramInv = value;
    }

    /**
     * Gets the value of the fechaAccidente property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaAccidente() {
        return fechaAccidente;
    }

    /**
     * Sets the value of the fechaAccidente property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaAccidente(XMLGregorianCalendar value) {
        this.fechaAccidente = value;
    }

    /**
     * Gets the value of the codigoTrayecto property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoTrayecto() {
        return codigoTrayecto;
    }

    /**
     * Sets the value of the codigoTrayecto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoTrayecto(BigInteger value) {
        this.codigoTrayecto = value;
    }

    /**
     * Gets the value of the fechaConcepcion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaConcepcion() {
        return fechaConcepcion;
    }

    /**
     * Sets the value of the fechaConcepcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaConcepcion(XMLGregorianCalendar value) {
        this.fechaConcepcion = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
