//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_ZONA_0 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_ZONA_0">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ZONA_01" type="{urn:www:lme:gov:cl:lme}CT_ZONA_01"/>
 *         &lt;element name="ZONA_0F" type="{urn:www:lme:gov:cl:lme}CT_ZONA_F"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_ZONA_0", propOrder = {
    "zona01",
    "zona0F"
})
public class CTZONA0 {

    @XmlElement(name = "ZONA_01", required = true)
    protected CTZONA01 zona01;
    @XmlElement(name = "ZONA_0F", required = true)
    protected CTZONAF zona0F;

    /**
     * Gets the value of the zona01 property.
     * 
     * @return
     *     possible object is
     *     {@link CTZONA01 }
     *     
     */
    public CTZONA01 getZONA01() {
        return zona01;
    }

    /**
     * Sets the value of the zona01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTZONA01 }
     *     
     */
    public void setZONA01(CTZONA01 value) {
        this.zona01 = value;
    }

    /**
     * Gets the value of the zona0F property.
     * 
     * @return
     *     possible object is
     *     {@link CTZONAF }
     *     
     */
    public CTZONAF getZONA0F() {
        return zona0F;
    }

    /**
     * Sets the value of the zona0F property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTZONAF }
     *     
     */
    public void setZONA0F(CTZONAF value) {
        this.zona0F = value;
    }

}
