//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 07:19:46 PM CLT 
//


package lme.gov.cl.lme;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CT_ZONA_C1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_ZONA_C1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="emp_nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emp_rut" type="{urn:www:lme:gov:cl:lme}STRut"/>
 *         &lt;element name="emp_telefono" type="{urn:www:lme:gov:cl:lme}CTTelefono" minOccurs="0"/>
 *         &lt;element name="emp_fecha_recepcion" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="emp_direccion" type="{urn:www:lme:gov:cl:lme}CTDireccion"/>
 *         &lt;element name="codigo_comuna_compin" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="codigo_actividad_laboral" type="{urn:www:lme:gov:cl:lme}STActividad_laboral" minOccurs="0"/>
 *         &lt;element name="codigo_ocupacion" type="{urn:www:lme:gov:cl:lme}STOcupacion" minOccurs="0"/>
 *         &lt;element name="emp_otra_ocupacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_ZONA_C1", propOrder = {
    "empNombre",
    "empRut",
    "empTelefono",
    "empFechaRecepcion",
    "empDireccion",
    "codigoComunaCompin",
    "codigoActividadLaboral",
    "codigoOcupacion",
    "empOtraOcupacion"
})
public class CTZONAC1 {

    @XmlElement(name = "emp_nombre", required = true)
    protected String empNombre;
    @XmlElement(name = "emp_rut", required = true)
    protected String empRut;
    @XmlElement(name = "emp_telefono")
    protected CTTelefono empTelefono;
    @XmlElement(name = "emp_fecha_recepcion")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar empFechaRecepcion;
    @XmlElement(name = "emp_direccion", required = true)
    protected CTDireccion empDireccion;
    @XmlElement(name = "codigo_comuna_compin")
    protected BigInteger codigoComunaCompin;
    @XmlElement(name = "codigo_actividad_laboral")
    protected BigInteger codigoActividadLaboral;
    @XmlElement(name = "codigo_ocupacion")
    protected BigInteger codigoOcupacion;
    @XmlElement(name = "emp_otra_ocupacion")
    protected String empOtraOcupacion;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the empNombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpNombre() {
        return empNombre;
    }

    /**
     * Sets the value of the empNombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpNombre(String value) {
        this.empNombre = value;
    }

    /**
     * Gets the value of the empRut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpRut() {
        return empRut;
    }

    /**
     * Sets the value of the empRut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpRut(String value) {
        this.empRut = value;
    }

    /**
     * Gets the value of the empTelefono property.
     * 
     * @return
     *     possible object is
     *     {@link CTTelefono }
     *     
     */
    public CTTelefono getEmpTelefono() {
        return empTelefono;
    }

    /**
     * Sets the value of the empTelefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTTelefono }
     *     
     */
    public void setEmpTelefono(CTTelefono value) {
        this.empTelefono = value;
    }

    /**
     * Gets the value of the empFechaRecepcion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEmpFechaRecepcion() {
        return empFechaRecepcion;
    }

    /**
     * Sets the value of the empFechaRecepcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEmpFechaRecepcion(XMLGregorianCalendar value) {
        this.empFechaRecepcion = value;
    }

    /**
     * Gets the value of the empDireccion property.
     * 
     * @return
     *     possible object is
     *     {@link CTDireccion }
     *     
     */
    public CTDireccion getEmpDireccion() {
        return empDireccion;
    }

    /**
     * Sets the value of the empDireccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTDireccion }
     *     
     */
    public void setEmpDireccion(CTDireccion value) {
        this.empDireccion = value;
    }

    /**
     * Gets the value of the codigoComunaCompin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoComunaCompin() {
        return codigoComunaCompin;
    }

    /**
     * Sets the value of the codigoComunaCompin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoComunaCompin(BigInteger value) {
        this.codigoComunaCompin = value;
    }

    /**
     * Gets the value of the codigoActividadLaboral property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoActividadLaboral() {
        return codigoActividadLaboral;
    }

    /**
     * Sets the value of the codigoActividadLaboral property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoActividadLaboral(BigInteger value) {
        this.codigoActividadLaboral = value;
    }

    /**
     * Gets the value of the codigoOcupacion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoOcupacion() {
        return codigoOcupacion;
    }

    /**
     * Sets the value of the codigoOcupacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoOcupacion(BigInteger value) {
        this.codigoOcupacion = value;
    }

    /**
     * Gets the value of the empOtraOcupacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpOtraOcupacion() {
        return empOtraOcupacion;
    }

    /**
     * Sets the value of the empOtraOcupacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpOtraOcupacion(String value) {
        this.empOtraOcupacion = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
