package cse.database.objects;

public class Condicionotorgamiento {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MotorCreditScoring.dbo.CondicionOtorgamiento.IdCondicion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private Integer idcondicion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MotorCreditScoring.dbo.CondicionOtorgamiento.Nombre
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private String nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MotorCreditScoring.dbo.CondicionOtorgamiento.Descripcion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private String descripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MotorCreditScoring.dbo.CondicionOtorgamiento.Vigente
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private Boolean vigente;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MotorCreditScoring.dbo.CondicionOtorgamiento.IdCondicion
     *
     * @return the value of MotorCreditScoring.dbo.CondicionOtorgamiento.IdCondicion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public Integer getIdcondicion() {
        return idcondicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MotorCreditScoring.dbo.CondicionOtorgamiento.IdCondicion
     *
     * @param idcondicion the value for MotorCreditScoring.dbo.CondicionOtorgamiento.IdCondicion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void setIdcondicion(Integer idcondicion) {
        this.idcondicion = idcondicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MotorCreditScoring.dbo.CondicionOtorgamiento.Nombre
     *
     * @return the value of MotorCreditScoring.dbo.CondicionOtorgamiento.Nombre
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MotorCreditScoring.dbo.CondicionOtorgamiento.Nombre
     *
     * @param nombre the value for MotorCreditScoring.dbo.CondicionOtorgamiento.Nombre
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MotorCreditScoring.dbo.CondicionOtorgamiento.Descripcion
     *
     * @return the value of MotorCreditScoring.dbo.CondicionOtorgamiento.Descripcion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MotorCreditScoring.dbo.CondicionOtorgamiento.Descripcion
     *
     * @param descripcion the value for MotorCreditScoring.dbo.CondicionOtorgamiento.Descripcion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MotorCreditScoring.dbo.CondicionOtorgamiento.Vigente
     *
     * @return the value of MotorCreditScoring.dbo.CondicionOtorgamiento.Vigente
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public Boolean getVigente() {
        return vigente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MotorCreditScoring.dbo.CondicionOtorgamiento.Vigente
     *
     * @param vigente the value for MotorCreditScoring.dbo.CondicionOtorgamiento.Vigente
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void setVigente(Boolean vigente) {
        this.vigente = vigente;
    }
}