package cse.database.objects;

public class Solicitudcondicionotorgamiento extends SolicitudcondicionotorgamientoKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.NombreCondicion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private String nombrecondicion;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.NombreCondicion
     *
     * @return the value of MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.NombreCondicion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public String getNombrecondicion() {
        return nombrecondicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.NombreCondicion
     *
     * @param nombrecondicion the value for MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.NombreCondicion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void setNombrecondicion(String nombrecondicion) {
        this.nombrecondicion = nombrecondicion == null ? null : nombrecondicion.trim();
    }
}