package cse.database.objects;

public class SolicitudcondicionotorgamientoKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.IdSolicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private String idsolicitud;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.IdCondicion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private Integer idcondicion;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.IdSolicitud
     *
     * @return the value of MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.IdSolicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public String getIdsolicitud() {
        return idsolicitud;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.IdSolicitud
     *
     * @param idsolicitud the value for MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.IdSolicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void setIdsolicitud(String idsolicitud) {
        this.idsolicitud = idsolicitud == null ? null : idsolicitud.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.IdCondicion
     *
     * @return the value of MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.IdCondicion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public Integer getIdcondicion() {
        return idcondicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.IdCondicion
     *
     * @param idcondicion the value for MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento.IdCondicion
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void setIdcondicion(Integer idcondicion) {
        this.idcondicion = idcondicion;
    }
}