package cse.database.dao;

import java.sql.SQLException;
import java.util.List;

import cse.database.dao.exception.DAOException;
import cse.database.objects.Solicitudcondicionotorgamiento;
import cse.database.objects.SolicitudcondicionotorgamientoKey;

public interface SolicitudcondicionotorgamientoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    int deleteByPrimaryKey(SolicitudcondicionotorgamientoKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    void insert(Solicitudcondicionotorgamiento record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    void insertSelective(Solicitudcondicionotorgamiento record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    Solicitudcondicionotorgamiento selectByPrimaryKey(SolicitudcondicionotorgamientoKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    int updateByPrimaryKey(Solicitudcondicionotorgamiento record) throws SQLException;

	List selectBySolicitud(String idSolicitud) throws DAOException;
}