<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" name="LicenciasMedicasService" targetNamespace="http://servicios.laaraucana.cl/licenciasMedicas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://servicios.laaraucana.cl/licenciasMedicas" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://servicios.laaraucana.cl/licenciasMedicas" schemaLocation="LicenciasMedicasService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="findLicencias">
    <part element="tns:findLicencias" name="parameters">
    </part>
  </message>
  <message name="SOAPException">
    <part element="tns:SOAPException" name="fault">
    </part>
  </message>
  <message name="findLicenciasResponse">
    <part element="tns:findLicenciasResponse" name="parameters">
    </part>
  </message>
  <portType name="LicenciasMedicasImpl">
    <operation name="findLicencias">
      <input message="tns:findLicencias" wsam:Action="http://servicios.laaraucana.cl/ivr/licenciasMedicas">
    </input>
      <output message="tns:findLicenciasResponse" wsam:Action="http://servicios.laaraucana.cl/licenciasMedicas/LicenciasMedicasImpl/findLicenciasResponse">
    </output>
      <fault message="tns:SOAPException" name="SOAPException" wsam:Action="http://servicios.laaraucana.cl/licenciasMedicas/LicenciasMedicasImpl/findLicencias/Fault/SOAPException">
    </fault>
    </operation>
  </portType>
  <binding name="LicenciasMedicasPortBinding" type="tns:LicenciasMedicasImpl">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="findLicencias">
      <soap:operation soapAction="http://servicios.laaraucana.cl/ivr/licenciasMedicas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="SOAPException">
        <soap:fault name="SOAPException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="LicenciasMedicasService">
    <port binding="tns:LicenciasMedicasPortBinding" name="LicenciasMedicasPort">
      <soap:address location="http://localhost:9080/WSLicenciasIVR/LicenciasMedicasService"/>
    </port>
  </service>
</definitions>