//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.araucana.bonomarzo.mgr.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "getBonoTrabajador", namespace = "http://servicios.laaraucana.cl/bonomarzo")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBonoTrabajador", namespace = "http://servicios.laaraucana.cl/bonomarzo")
public class GetBonoTrabajador {

    @XmlElement(name = "request", namespace = "", required = true)
    private cl.araucana.bonomarzo.vo.RequestWS request;

    /**
     * 
     * @return
     *     returns RequestWS
     */
    public cl.araucana.bonomarzo.vo.RequestWS getRequest() {
        return this.request;
    }

    /**
     * 
     * @param request
     *     the value for the request property
     */
    public void setRequest(cl.araucana.bonomarzo.vo.RequestWS request) {
        this.request = request;
    }

}
