//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.benef.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "consultaBeneficio", namespace = "http://servicio.laaraucana.cl/benef")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultaBeneficio", namespace = "http://servicio.laaraucana.cl/benef", propOrder = {
    "token",
    "codigoBENEFICIO"
})
public class ConsultaBeneficio {

    @XmlElement(name = "TOKEN", namespace = "", required = true)
    private String token;
    @XmlElement(name = "CODIGO_BENEFICIO", namespace = "", required = true)
    private String codigoBENEFICIO;

    /**
     * 
     * @return
     *     returns String
     */
    public String getToken() {
        return this.token;
    }

    /**
     * 
     * @param token
     *     the value for the token property
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getCodigoBENEFICIO() {
        return this.codigoBENEFICIO;
    }

    /**
     * 
     * @param codigoBENEFICIO
     *     the value for the codigoBENEFICIO property
     */
    public void setCodigoBENEFICIO(String codigoBENEFICIO) {
        this.codigoBENEFICIO = codigoBENEFICIO;
    }

}
