//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.simulacion.webservices.autogenerado.consultadatosafiliacion;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consultaDatosAfiliacionAs400SalidaVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consultaDatosAfiliacionAs400SalidaVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="detalleEmpresa" type="{http://delegate.toAS.legados.integracion.laaraucana.cl/}detalleConsultaDatosAfiliacionAs400SalidaVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="log" type="{http://delegate.toAS.legados.integracion.laaraucana.cl/}log" minOccurs="0"/>
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resultCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalEmpresa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultaDatosAfiliacionAs400SalidaVO", propOrder = {
    "detalleEmpresa",
    "log",
    "nombre",
    "resultCode",
    "totalEmpresa"
})
public class ConsultaDatosAfiliacionAs400SalidaVO {

    @XmlElement(nillable = true)
    protected List<DetalleConsultaDatosAfiliacionAs400SalidaVO> detalleEmpresa;
    protected Log log;
    protected String nombre;
    protected String resultCode;
    protected String totalEmpresa;

    /**
     * Gets the value of the detalleEmpresa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detalleEmpresa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetalleEmpresa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetalleConsultaDatosAfiliacionAs400SalidaVO }
     * 
     * 
     */
    public List<DetalleConsultaDatosAfiliacionAs400SalidaVO> getDetalleEmpresa() {
        if (detalleEmpresa == null) {
            detalleEmpresa = new ArrayList<DetalleConsultaDatosAfiliacionAs400SalidaVO>();
        }
        return this.detalleEmpresa;
    }

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link Log }
     *     
     */
    public Log getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link Log }
     *     
     */
    public void setLog(Log value) {
        this.log = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the totalEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalEmpresa() {
        return totalEmpresa;
    }

    /**
     * Sets the value of the totalEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalEmpresa(String value) {
        this.totalEmpresa = value;
    }

}
