package cl.laaraucana.recepcionsil.persistencia.dto;

public class CopyOfIlfsering {

	private String afirut;
	private Long numimpre;
	private Integer lichasfec;
	private Short codest;
	private String gloest;
	private Long fhingjav;
	private Long fhingas4;
	private Integer reintento;
	private String sapcrm;

	public String getAfirut() {
		return afirut;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column OPE05701.ILFSERING.AFIRUT
	 * @param afirut  the value for OPE05701.ILFSERING.AFIRUT
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public void setAfirut(String afirut) {
		this.afirut = afirut;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column OPE05701.ILFSERING.NUMIMPRE
	 * @return  the value of OPE05701.ILFSERING.NUMIMPRE
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public Long getNumimpre() {
		return numimpre;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column OPE05701.ILFSERING.NUMIMPRE
	 * @param numimpre  the value for OPE05701.ILFSERING.NUMIMPRE
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public void setNumimpre(Long numimpre) {
		this.numimpre = numimpre;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column OPE05701.ILFSERING.LICHASFEC
	 * @return  the value of OPE05701.ILFSERING.LICHASFEC
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public Integer getLichasfec() {
		return lichasfec;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column OPE05701.ILFSERING.LICHASFEC
	 * @param lichasfec  the value for OPE05701.ILFSERING.LICHASFEC
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public void setLichasfec(Integer lichasfec) {
		this.lichasfec = lichasfec;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column OPE05701.ILFSERING.CODEST
	 * @return  the value of OPE05701.ILFSERING.CODEST
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public Short getCodest() {
		return codest;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column OPE05701.ILFSERING.CODEST
	 * @param codest  the value for OPE05701.ILFSERING.CODEST
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public void setCodest(Short codest) {
		this.codest = codest;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column OPE05701.ILFSERING.GLOEST
	 * @return  the value of OPE05701.ILFSERING.GLOEST
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public String getGloest() {
		return gloest;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column OPE05701.ILFSERING.GLOEST
	 * @param gloest  the value for OPE05701.ILFSERING.GLOEST
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public void setGloest(String gloest) {
		this.gloest = gloest;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column OPE05701.ILFSERING.FHINGJAV
	 * @return  the value of OPE05701.ILFSERING.FHINGJAV
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public Long getFhingjav() {
		return fhingjav;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column OPE05701.ILFSERING.FHINGJAV
	 * @param fhingjav  the value for OPE05701.ILFSERING.FHINGJAV
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public void setFhingjav(Long fhingjav) {
		this.fhingjav = fhingjav;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column OPE05701.ILFSERING.FHINGAS4
	 * @return  the value of OPE05701.ILFSERING.FHINGAS4
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public Long getFhingas4() {
		return fhingas4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column OPE05701.ILFSERING.FHINGAS4
	 * @param fhingas4  the value for OPE05701.ILFSERING.FHINGAS4
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public void setFhingas4(Long fhingas4) {
		this.fhingas4 = fhingas4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column OPE05701.ILFSERING.REINTENTO
	 * @return  the value of OPE05701.ILFSERING.REINTENTO
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public Integer getReintento() {
		return reintento;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column OPE05701.ILFSERING.REINTENTO
	 * @param reintento  the value for OPE05701.ILFSERING.REINTENTO
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public void setReintento(Integer reintento) {
		this.reintento = reintento;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column OPE05701.ILFSERING.SAPCRM
	 * @return  the value of OPE05701.ILFSERING.SAPCRM
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public String getSapcrm() {
		return sapcrm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column OPE05701.ILFSERING.SAPCRM
	 * @param sapcrm  the value for OPE05701.ILFSERING.SAPCRM
	 * @abatorgenerated  Tue May 12 14:43:19 ART 2015
	 */
	public void setSapcrm(String sapcrm) {
		this.sapcrm = sapcrm;
	}

}