package cl.laaraucana.recepcionsil.persistencia.dto;

public class IlfseringExample extends Ilfsering {
	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public static final int EXAMPLE_IGNORE = 0;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public static final int EXAMPLE_NULL = 1;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public static final int EXAMPLE_NOT_NULL = 2;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public static final int EXAMPLE_EQUALS = 3;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public static final int EXAMPLE_NOT_EQUALS = 4;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public static final int EXAMPLE_GREATER_THAN = 5;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public static final int EXAMPLE_LESS_THAN = 7;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public static final int EXAMPLE_LIKE = 9;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	private boolean combineTypeOr;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	private int afirut_Indicator;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	private int numimpre_Indicator;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	private int lichasfec_Indicator;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	private int codest_Indicator;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	private int gloest_Indicator;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	private int fhingjav_Indicator;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	private int fhingas4_Indicator;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	private int reintento_Indicator;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	private int sapcrm_Indicator;

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public void setCombineTypeOr(boolean combineTypeOr) {
		this.combineTypeOr = combineTypeOr;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public boolean isCombineTypeOr() {
		return combineTypeOr;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public int getAfirut_Indicator() {
		return afirut_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public void setAfirut_Indicator(int afirut_Indicator) {
		this.afirut_Indicator = afirut_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public int getNumimpre_Indicator() {
		return numimpre_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public void setNumimpre_Indicator(int numimpre_Indicator) {
		this.numimpre_Indicator = numimpre_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public int getLichasfec_Indicator() {
		return lichasfec_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public void setLichasfec_Indicator(int lichasfec_Indicator) {
		this.lichasfec_Indicator = lichasfec_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public int getCodest_Indicator() {
		return codest_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public void setCodest_Indicator(int codest_Indicator) {
		this.codest_Indicator = codest_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public int getGloest_Indicator() {
		return gloest_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public void setGloest_Indicator(int gloest_Indicator) {
		this.gloest_Indicator = gloest_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public int getFhingjav_Indicator() {
		return fhingjav_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public void setFhingjav_Indicator(int fhingjav_Indicator) {
		this.fhingjav_Indicator = fhingjav_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public int getFhingas4_Indicator() {
		return fhingas4_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public void setFhingas4_Indicator(int fhingas4_Indicator) {
		this.fhingas4_Indicator = fhingas4_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public int getReintento_Indicator() {
		return reintento_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public void setReintento_Indicator(int reintento_Indicator) {
		this.reintento_Indicator = reintento_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public int getSapcrm_Indicator() {
		return sapcrm_Indicator;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table OPE05701.ILFSERING
	 *
	 * @abatorgenerated Tue May 12 14:43:19 ART 2015
	 */
	public void setSapcrm_Indicator(int sapcrm_Indicator) {
		this.sapcrm_Indicator = sapcrm_Indicator;
	}
}