//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.araucana.tupla2.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "extingueCausantesResponse", namespace = "http://servicios.laaraucana.cl/extincionSIAGF")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "extingueCausantesResponse", namespace = "http://servicios.laaraucana.cl/extincionSIAGF")
public class SetExtingueCausantesResponse {

    @XmlElement(name = "return", namespace = "")
    private cl.araucana.wssiagf.vo.ResponseWS _return;

    /**
     * 
     * @return
     *     returns ResponseWS
     */
    public cl.araucana.wssiagf.vo.ResponseWS getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(cl.araucana.wssiagf.vo.ResponseWS _return) {
        this._return = _return;
    }

}
