//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.araucana.tupla2.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "extingueCausantes", namespace = "http://servicios.laaraucana.cl/extincionSIAGF")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "extingueCausantes", namespace = "http://servicios.laaraucana.cl/extincionSIAGF", propOrder = {
    "token",
    "request"
})
public class SetExtingueCausantes {

    @XmlElement(name = "token", namespace = "", required = true)
    private String token;
    @XmlElement(name = "request", namespace = "", required = true)
    private cl.araucana.wssiagf.vo.RequestWS request;

    /**
     * 
     * @return
     *     returns String
     */
    public String getToken() {
        return this.token;
    }

    /**
     * 
     * @param token
     *     the value for the token property
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * 
     * @return
     *     returns RequestWS
     */
    public cl.araucana.wssiagf.vo.RequestWS getRequest() {
        return this.request;
    }

    /**
     * 
     * @param request
     *     the value for the request property
     */
    public void setRequest(cl.araucana.wssiagf.vo.RequestWS request) {
        this.request = request;
    }

}
