//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.recepcionsil.service.delegate.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "ingresoLicencia", namespace = "http://delegate.service.recepcionsil.laaraucana.cl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ingresoLicencia", namespace = "http://delegate.service.recepcionsil.laaraucana.cl/")
public class IngresoLicencia {

    @XmlElement(name = "arg0", namespace = "")
    private cl.laaraucana.recepcionsil.service.vo.EntradaRecepcionSILVO arg0;

    /**
     * 
     * @return
     *     returns EntradaRecepcionSILVO
     */
    public cl.laaraucana.recepcionsil.service.vo.EntradaRecepcionSILVO getArg0() {
        return this.arg0;
    }

    /**
     * 
     * @param arg0
     *     the value for the arg0 property
     */
    public void setArg0(cl.laaraucana.recepcionsil.service.vo.EntradaRecepcionSILVO arg0) {
        this.arg0 = arg0;
    }

}
