//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.laaraucana.compromisototal.webservice.autogenerado.as400.detalle;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.laaraucana.compromisototal.integracion.as400.detalle package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConsultaCreditoPorFolioEnAs400Response_QNAME = new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "consultaCreditoPorFolioEnAs400Response");
    private final static QName _ConsultaCreditoPorFolioEnAs400_QNAME = new QName("http://delegate.toAS.legados.integracion.laaraucana.cl/", "consultaCreditoPorFolioEnAs400");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.laaraucana.compromisototal.integracion.as400.detalle
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultaCreditoPorFolioEnAs400_Type }
     * 
     */
    public ConsultaCreditoPorFolioEnAs400_Type createConsultaCreditoPorFolioEnAs400_Type() {
        return new ConsultaCreditoPorFolioEnAs400_Type();
    }

    /**
     * Create an instance of {@link ConsultaCreditoPorFolioEnAs400Response }
     * 
     */
    public ConsultaCreditoPorFolioEnAs400Response createConsultaCreditoPorFolioEnAs400Response() {
        return new ConsultaCreditoPorFolioEnAs400Response();
    }

    /**
     * Create an instance of {@link DetalleConsultaCreditoPorFolioSalidaVO }
     * 
     */
    public DetalleConsultaCreditoPorFolioSalidaVO createDetalleConsultaCreditoPorFolioSalidaVO() {
        return new DetalleConsultaCreditoPorFolioSalidaVO();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link ConsultaCreditoPorFolioSalidaVO }
     * 
     */
    public ConsultaCreditoPorFolioSalidaVO createConsultaCreditoPorFolioSalidaVO() {
        return new ConsultaCreditoPorFolioSalidaVO();
    }

    /**
     * Create an instance of {@link ConsultaCreditoPorFolioEntradaVO }
     * 
     */
    public ConsultaCreditoPorFolioEntradaVO createConsultaCreditoPorFolioEntradaVO() {
        return new ConsultaCreditoPorFolioEntradaVO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaCreditoPorFolioEnAs400Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", name = "consultaCreditoPorFolioEnAs400Response")
    public JAXBElement<ConsultaCreditoPorFolioEnAs400Response> createConsultaCreditoPorFolioEnAs400Response(ConsultaCreditoPorFolioEnAs400Response value) {
        return new JAXBElement<ConsultaCreditoPorFolioEnAs400Response>(_ConsultaCreditoPorFolioEnAs400Response_QNAME, ConsultaCreditoPorFolioEnAs400Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaCreditoPorFolioEnAs400_Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://delegate.toAS.legados.integracion.laaraucana.cl/", name = "consultaCreditoPorFolioEnAs400")
    public JAXBElement<ConsultaCreditoPorFolioEnAs400_Type> createConsultaCreditoPorFolioEnAs400(ConsultaCreditoPorFolioEnAs400_Type value) {
        return new JAXBElement<ConsultaCreditoPorFolioEnAs400_Type>(_ConsultaCreditoPorFolioEnAs400_QNAME, ConsultaCreditoPorFolioEnAs400_Type.class, null, value);
    }

}
