package cse.database.dao.ibatis.impl;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;

import cse.database.dao.ClasificacionempresaDAO;
import cse.database.dao.exception.DAOException;
import cse.database.objects.Clasificacionempresa;

public class ClasificacionempresaDAOImpl_IBatis implements ClasificacionempresaDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MotorCreditScoring.dbo.ClasificacionEmpresa
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.ClasificacionEmpresa
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public ClasificacionempresaDAOImpl_IBatis(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.ClasificacionEmpresa
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public int deleteByPrimaryKey(Integer idclasificacionempresa) throws SQLException {
        Clasificacionempresa key = new Clasificacionempresa();
        key.setIdclasificacionempresa(idclasificacionempresa);
        int rows = sqlMapClient.delete("MotorCreditScoring_dbo_ClasificacionEmpresa.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.ClasificacionEmpresa
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void insert(Clasificacionempresa record) throws SQLException {
        sqlMapClient.insert("MotorCreditScoring_dbo_ClasificacionEmpresa.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.ClasificacionEmpresa
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void insertSelective(Clasificacionempresa record) throws SQLException {
        sqlMapClient.insert("MotorCreditScoring_dbo_ClasificacionEmpresa.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.ClasificacionEmpresa
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public Clasificacionempresa selectByPrimaryKey(Integer idclasificacionempresa) throws SQLException {
        Clasificacionempresa key = new Clasificacionempresa();
        key.setIdclasificacionempresa(idclasificacionempresa);
        Clasificacionempresa record = (Clasificacionempresa) sqlMapClient.queryForObject("MotorCreditScoring_dbo_ClasificacionEmpresa.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.ClasificacionEmpresa
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public int updateByPrimaryKey(Clasificacionempresa record) throws SQLException {
        int rows = sqlMapClient.update("MotorCreditScoring_dbo_ClasificacionEmpresa.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public List selectByNombre(String nombre) throws SQLException, DAOException {
		// TODO Auto-generated method stub
		return null;
	}
}