package cse.database.dao.ibatis.impl;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;

import cse.database.dao.EstadocivilDAO;
import cse.database.dao.exception.DAOException;
import cse.database.objects.Estadocivil;

public class EstadocivilDAOImpl_IBatis implements EstadocivilDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MotorCreditScoring.dbo.EstadoCivil
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.EstadoCivil
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public EstadocivilDAOImpl_IBatis(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.EstadoCivil
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public int deleteByPrimaryKey(Integer idestadocivil) throws SQLException {
        Estadocivil key = new Estadocivil();
        key.setIdestadocivil(idestadocivil);
        int rows = sqlMapClient.delete("MotorCreditScoring_dbo_EstadoCivil.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.EstadoCivil
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void insert(Estadocivil record) throws SQLException {
        sqlMapClient.insert("MotorCreditScoring_dbo_EstadoCivil.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.EstadoCivil
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void insertSelective(Estadocivil record) throws SQLException {
        sqlMapClient.insert("MotorCreditScoring_dbo_EstadoCivil.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.EstadoCivil
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public Estadocivil selectByPrimaryKey(Integer idestadocivil) throws SQLException {
        Estadocivil key = new Estadocivil();
        key.setIdestadocivil(idestadocivil);
        Estadocivil record = (Estadocivil) sqlMapClient.queryForObject("MotorCreditScoring_dbo_EstadoCivil.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.EstadoCivil
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public int updateByPrimaryKey(Estadocivil record) throws SQLException {
        int rows = sqlMapClient.update("MotorCreditScoring_dbo_EstadoCivil.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public List selectByNombre(String estadoCivil) throws SQLException, DAOException {
		// TODO Auto-generated method stub
		return null;
	}
}