package cse.database.dao.ibatis.impl;

import java.sql.SQLException;
import java.sql.Timestamp;

import com.ibatis.sqlmap.client.SqlMapClient;

import cse.database.dao.SolicitudDAO;
import cse.database.dao.exception.DAOException;
import cse.database.dao.jdbc.JdbcUtil;
import cse.database.objects.Solicitud;

public class SolicitudDAOImpl_IBatis implements SolicitudDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MotorCreditScoring.dbo.Solicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.Solicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public SolicitudDAOImpl_IBatis(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.Solicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public int deleteByPrimaryKey(String idsolicitud) throws SQLException {
        Solicitud key = new Solicitud();
        key.setIdsolicitud(idsolicitud);
        int rows = sqlMapClient.delete("MotorCreditScoring_dbo_Solicitud.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.Solicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void insert(Solicitud record) throws SQLException {
        sqlMapClient.insert("MotorCreditScoring_dbo_Solicitud.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.Solicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void insertSelective(Solicitud record) throws SQLException {
        sqlMapClient.insert("MotorCreditScoring_dbo_Solicitud.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.Solicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public Solicitud selectByPrimaryKey(String idsolicitud) throws DAOException {
        Solicitud key = new Solicitud();
        key.setIdsolicitud(idsolicitud);
        Solicitud record;
		try {
			record = (Solicitud) sqlMapClient.queryForObject("MotorCreditScoring_dbo_Solicitud.ibatorgenerated_selectByPrimaryKey", key);
		} catch (SQLException e) {
			throw new DAOException(e);
			
		}
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.Solicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public int updateByPrimaryKeySelective(Solicitud record) throws SQLException {
        int rows = sqlMapClient.update("MotorCreditScoring_dbo_Solicitud.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.Solicitud
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public int updateByPrimaryKey(Solicitud record) throws SQLException {
        int rows = sqlMapClient.update("MotorCreditScoring_dbo_Solicitud.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public String createNewSolicitud() throws SQLException, DAOException {	
		String idSolicitud = JdbcUtil.getUniqueSolicitudId(null);
		Solicitud newRecord = new Solicitud();
		newRecord.setIdsolicitud(idSolicitud);
		newRecord.setFechacreacion(new Timestamp(new
				java.util.Date().getTime()));
		insert(newRecord);
		return idSolicitud;
	}
}