package cse.database.dao.ibatis.impl;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;

import cse.database.dao.SolicitudcondicionotorgamientoDAO;
import cse.database.dao.exception.DAOException;
import cse.database.objects.Solicitudcondicionotorgamiento;
import cse.database.objects.SolicitudcondicionotorgamientoKey;

public class SolicitudcondicionotorgamientoDAOImpl_IBatis implements SolicitudcondicionotorgamientoDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public SolicitudcondicionotorgamientoDAOImpl_IBatis(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public int deleteByPrimaryKey(SolicitudcondicionotorgamientoKey key) throws SQLException {
        int rows = sqlMapClient.delete("MotorCreditScoring_dbo_SolicitudCondicionOtorgamiento.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void insert(Solicitudcondicionotorgamiento record) throws SQLException {
        sqlMapClient.insert("MotorCreditScoring_dbo_SolicitudCondicionOtorgamiento.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public void insertSelective(Solicitudcondicionotorgamiento record) throws SQLException {
        sqlMapClient.insert("MotorCreditScoring_dbo_SolicitudCondicionOtorgamiento.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public Solicitudcondicionotorgamiento selectByPrimaryKey(SolicitudcondicionotorgamientoKey key) throws SQLException {
        Solicitudcondicionotorgamiento record = (Solicitudcondicionotorgamiento) sqlMapClient.queryForObject("MotorCreditScoring_dbo_SolicitudCondicionOtorgamiento.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MotorCreditScoring.dbo.SolicitudCondicionOtorgamiento
     *
     * @ibatorgenerated Wed Apr 25 16:42:26 ADT 2012
     */
    public int updateByPrimaryKey(Solicitudcondicionotorgamiento record) throws SQLException {
        int rows = sqlMapClient.update("MotorCreditScoring_dbo_SolicitudCondicionOtorgamiento.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public List selectBySolicitud(String idSolicitud) throws DAOException {
    	List list = null;
		try {
			list = sqlMapClient.queryForList("MotorCreditScoring_dbo_SolicitudCondicionOtorgamiento.ibatorgenerated_selectBySolicitud", idSolicitud);
		} catch (SQLException e) {
			throw new DAOException(e);
		}
        return list;
        
	}
}