drop table PERSONA;

CREATE TABLE PERSONA ( 
	ID_PERSONA DECIMAL(9, 0)  , 
	ID_COMUNA SMALLINT  , 
	ES_ADMIN_ARAU  SMALLINT  DEFAULT 0 , 
	CELULAR DECIMAL(9, 0)  DEFAULT 0 , 
	NUMERO CHAR(6)   DEFAULT '' , 
	DEPARTAMENTO  CHAR(6)   DEFAULT '' , 
	TELEFONO CHAR(15)   DEFAULT '' , 
	FAX CHAR(15)   DEFAULT '' , 
	NOMBRES CHAR(30)   , 
	APELLIDO_PATERNO CHAR(20)   DEFAULT '' , 
	APELLIDO_MATERNO CHAR(20)   DEFAULT '' , 
	EMAIL CHAR(100)   DEFAULT '' , 
	DIRECCION CHAR(80)   DEFAULT '' , 
	ES_ADMIN_CAJA  SMALLINT  DEFAULT 0 

) ; 
