DROP TABLE SUCURSAL;
CREATE TABLE SUCURSAL ( 
	ID_EMPRESA DECIMAL(9, 0), 
	ID_SUCURSAL CHAR(6), 
	ID_COMUNA SMALLINT, 
	NOMBRE CHAR(30) , 
	EMAIL CHAR(100) , 
	TELEFONO CHAR(15) , 
	CELULAR DECIMAL(9, 0), 
	FAX CHAR(15) , 
	DIRECCION CHAR(80) , 
	NUMERO CHAR(6)  , 
	DEPARTAMENTO CHAR(6)  
) ; 
