//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.lautaro.xi.bs.web_mobile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lautaro.xi.bs.web_mobile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QueryCompactContractHeaderRequestOut_QNAME = new QName("http://lautaro.com/xi/BS/WEB-Mobile", "QueryCompactContractHeaderRequestOut");
    private final static QName _QueryCompactContractHeaderResponseOut2_QNAME = new QName("http://lautaro.com/xi/BS/WEB-Mobile", "QueryCompactContractHeaderResponseOut2");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lautaro.xi.bs.web_mobile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryCompactContractHeaderRequest }
     * 
     */
    public QueryCompactContractHeaderRequest createQueryCompactContractHeaderRequest() {
        return new QueryCompactContractHeaderRequest();
    }

    /**
     * Create an instance of {@link QueryCompactContractHeaderResponse2 }
     * 
     */
    public QueryCompactContractHeaderResponse2 createQueryCompactContractHeaderResponse2() {
        return new QueryCompactContractHeaderResponse2();
    }

    /**
     * Create an instance of {@link QueryCompactContractHeader2 }
     * 
     */
    public QueryCompactContractHeader2 createQueryCompactContractHeader2() {
        return new QueryCompactContractHeader2();
    }

    /**
     * Create an instance of {@link QueryCompactContract }
     * 
     */
    public QueryCompactContract createQueryCompactContract() {
        return new QueryCompactContract();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryCompactContractHeaderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lautaro.com/xi/BS/WEB-Mobile", name = "QueryCompactContractHeaderRequestOut")
    public JAXBElement<QueryCompactContractHeaderRequest> createQueryCompactContractHeaderRequestOut(QueryCompactContractHeaderRequest value) {
        return new JAXBElement<QueryCompactContractHeaderRequest>(_QueryCompactContractHeaderRequestOut_QNAME, QueryCompactContractHeaderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryCompactContractHeaderResponse2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lautaro.com/xi/BS/WEB-Mobile", name = "QueryCompactContractHeaderResponseOut2")
    public JAXBElement<QueryCompactContractHeaderResponse2> createQueryCompactContractHeaderResponseOut2(QueryCompactContractHeaderResponse2 value) {
        return new JAXBElement<QueryCompactContractHeaderResponse2>(_QueryCompactContractHeaderResponseOut2_QNAME, QueryCompactContractHeaderResponse2 .class, null, value);
    }

}
