// Tie class generated by rmic, do not edit.
// Contents subject to change without notice.

package cl.araucana.cp.distribuidor.business.ejbs;

import cl.araucana.cp.distribuidor.hibernate.beans.CotizanteVO;
import cl.araucana.cp.distribuidor.hibernate.beans.NodoVO;
import cl.araucana.cp.distribuidor.hibernate.exceptions.DaoException;
import java.io.Serializable;
import java.lang.Object;
import java.lang.String;
import java.lang.StringBuffer;
import java.lang.Throwable;
import java.rmi.Remote;
import java.util.HashMap;
import java.util.List;
import java.util.Properties;
import javax.ejb.EJBHome;
import javax.ejb.EJBObject;
import javax.ejb.Handle;
import javax.ejb.RemoveException;
import javax.rmi.CORBA.Tie;
import javax.rmi.CORBA.Util;
import org.omg.CORBA.BAD_OPERATION;
import org.omg.CORBA.ORB;
import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.Delegate;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.ResponseHandler;
import org.omg.CORBA.portable.UnknownException;

public class _EJSRemoteStatelessDistribuidorSession_b6b3452b_Tie extends org.omg.CORBA_2_3.portable.ObjectImpl implements Tie {
    
    private EJSRemoteStatelessDistribuidorSession_b6b3452b target = null;
    private ORB orb = null;
    
    private static final String[] _type_ids = {
        "RMI:cl.araucana.cp.distribuidor.business.ejbs.DistribuidorSession:0000000000000000", 
        "RMI:javax.ejb.EJBObject:0000000000000000", 
        "RMI:com.ibm.websphere.csi.CSIServant:0000000000000000", 
        "RMI:com.ibm.websphere.csi.TransactionalObject:0000000000000000"
    };
    
    public void setTarget(Remote target) {
        this.target = (EJSRemoteStatelessDistribuidorSession_b6b3452b) target;
    }
    
    public Remote getTarget() {
        return target;
    }
    
    public org.omg.CORBA.Object thisObject() {
        return this;
    }
    
    public void deactivate() {
        if (orb != null) {
            orb.disconnect(this);
            _set_delegate(null);
        }
    }
    
    public ORB orb() {
        return _orb();
    }
    
    public void orb(ORB orb) {
        orb.connect(this);
    }
    
    public void _set_delegate(Delegate del) {
        super._set_delegate(del);
        if (del != null)
            orb = _orb();
        else
            orb = null;
    }
    
    public String[] _ids() { 
        return _type_ids;
    }
    
    public OutputStream _invoke(String method, InputStream _in, ResponseHandler reply) throws SystemException {
        try {
            org.omg.CORBA_2_3.portable.InputStream in = 
                (org.omg.CORBA_2_3.portable.InputStream) _in;
            switch (method.length()) {
                case 6: 
                    if (method.equals("remove")) {
                        return remove(in, reply);
                    }
                case 8: 
                    if (method.equals("_get_env")) {
                        return _get_env(in, reply);
                    }
                case 11: 
                    if (method.equals("_get_handle")) {
                        return _get_handle(in, reply);
                    } else if (method.equals("isIdentical")) {
                        return isIdentical(in, reply);
                    } else if (method.equals("validaCarga")) {
                        return validaCarga(in, reply);
                    }
                case 12: 
                    if (method.equals("_get_EJBHome")) {
                        return _get_EJBHome(in, reply);
                    }
                case 15: 
                    if (method.equals("_get_primaryKey")) {
                        return _get_primaryKey(in, reply);
                    } else if (method.equals("getEstadisticas")) {
                        return getEstadisticas(in, reply);
                    }
                case 17: 
                    if (method.equals("eliminaTrabajador")) {
                        return eliminaTrabajador(in, reply);
                    } else if (method.equals("actualizaBalanceo")) {
                        return actualizaBalanceo(in, reply);
                    }
                case 18: 
                    if (method.equals("cargaConfiguracion")) {
                        return cargaConfiguracion(in, reply);
                    }
                case 26: 
                    if (method.equals("asigna__CORBA_WStringValue")) {
                        return asigna__CORBA_WStringValue(in, reply);
                    }
                case 31: 
                    if (method.equals("limpiaCache__CORBA_WStringValue")) {
                        return limpiaCache__CORBA_WStringValue(in, reply);
                    }
                case 32: 
                    if (method.equals("asigna__long__CORBA_WStringValue")) {
                        return asigna__long__CORBA_WStringValue(in, reply);
                    }
                case 51: 
                    if (method.equals("limpiaCache__CORBA_WStringValue__CORBA_WStringValue")) {
                        return limpiaCache__CORBA_WStringValue__CORBA_WStringValue(in, reply);
                    }
                case 68: 
                    if (method.equals("valida__CORBA_WStringValue__CORBA_WStringValue__java_util_Properties")) {
                        return valida__CORBA_WStringValue__CORBA_WStringValue__java_util_Properties(in, reply);
                    }
                case 109: 
                    if (method.equals("valida__long__CORBA_WStringValue__CORBA_WStringValue__cl_araucana_cp_distribuidor_hibernate_beans_CotizanteVO")) {
                        return valida__long__CORBA_WStringValue__CORBA_WStringValue__cl_araucana_cp_distribuidor_hibernate_beans_CotizanteVO(in, reply);
                    }
                case 115: 
                    if (method.equals("valida__long__CORBA_WStringValue__CORBA_WStringValue__cl_araucana_cp_distribuidor_hibernate_beans_CotizanteVO__long")) {
                        return valida__long__CORBA_WStringValue__CORBA_WStringValue__cl_araucana_cp_distribuidor_hibernate_beans_CotizanteVO__long(in, reply);
                    }
            }
            throw new BAD_OPERATION();
        } catch (SystemException ex) {
            throw ex;
        } catch (Throwable ex) {
            throw new UnknownException(ex);
        }
    }
    
    private OutputStream _get_EJBHome(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        EJBHome result = target.getEJBHome();
        OutputStream out = reply.createReply();
        Util.writeRemoteObject(out,result);
        return out;
    }
    
    private OutputStream _get_primaryKey(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        Object result = target.getPrimaryKey();
        OutputStream out = reply.createReply();
        Util.writeAny(out,result);
        return out;
    }
    
    private OutputStream remove(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        try {
            target.remove();
        } catch (RemoveException ex) {
            String id = "IDL:javax/ejb/RemoveEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,RemoveException.class);
            return out;
        }
        OutputStream out = reply.createReply();
        return out;
    }
    
    private OutputStream _get_handle(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        Handle result = target.getHandle();
        OutputStream out = reply.createReply();
        Util.writeAbstractObject(out,result);
        return out;
    }
    
    private OutputStream isIdentical(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        EJBObject arg0 = (EJBObject) in.read_Object(EJBObject.class);
        boolean result = target.isIdentical(arg0);
        OutputStream out = reply.createReply();
        out.write_boolean(result);
        return out;
    }
    
    private OutputStream _get_env(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        StringBuffer result = target.getEnv();
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,StringBuffer.class);
        return out;
    }
    
    private OutputStream asigna__CORBA_WStringValue(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        String arg0 = (String) in.read_value(String.class);
        NodoVO result;
        try {
            result = target.asigna(arg0);
        } catch (DaoException ex) {
            String id = "IDL:cl/araucana/cp/distribuidor/hibernate/exceptions/DaoEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,DaoException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,NodoVO.class);
        return out;
    }
    
    private OutputStream getEstadisticas(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        String arg0 = (String) in.read_value(String.class);
        List result = target.getEstadisticas(arg0);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,List.class);
        return out;
    }
    
    private OutputStream limpiaCache__CORBA_WStringValue__CORBA_WStringValue(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        String arg0 = (String) in.read_value(String.class);
        String arg1 = (String) in.read_value(String.class);
        target.limpiaCache(arg0, arg1);
        OutputStream out = reply.createReply();
        return out;
    }
    
    private OutputStream eliminaTrabajador(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        boolean arg0 = in.read_boolean();
        int arg1 = in.read_long();
        int arg2 = in.read_long();
        char arg3 = in.read_wchar();
        int arg4 = in.read_long();
        String arg5 = (String) in.read_value(String.class);
        int arg6 = in.read_long();
        int result = target.eliminaTrabajador(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
        OutputStream out = reply.createReply();
        out.write_long(result);
        return out;
    }
    
    private OutputStream limpiaCache__CORBA_WStringValue(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        String arg0 = (String) in.read_value(String.class);
        target.limpiaCache(arg0);
        OutputStream out = reply.createReply();
        return out;
    }
    
    private OutputStream cargaConfiguracion(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        boolean result;
        try {
            result = target.cargaConfiguracion();
        } catch (DaoException ex) {
            String id = "IDL:cl/araucana/cp/distribuidor/hibernate/exceptions/DaoEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,DaoException.class);
            return out;
        }
        OutputStream out = reply.createReply();
        out.write_boolean(result);
        return out;
    }
    
    private OutputStream actualizaBalanceo(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        String arg0 = (String) in.read_value(String.class);
        boolean result;
        try {
            result = target.actualizaBalanceo(arg0);
        } catch (DaoException ex) {
            String id = "IDL:cl/araucana/cp/distribuidor/hibernate/exceptions/DaoEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,DaoException.class);
            return out;
        }
        OutputStream out = reply.createReply();
        out.write_boolean(result);
        return out;
    }
    
    private OutputStream asigna__long__CORBA_WStringValue(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        int arg0 = in.read_long();
        String arg1 = (String) in.read_value(String.class);
        HashMap result;
        try {
            result = target.asigna(arg0, arg1);
        } catch (DaoException ex) {
            String id = "IDL:cl/araucana/cp/distribuidor/hibernate/exceptions/DaoEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,DaoException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,HashMap.class);
        return out;
    }
    
    private OutputStream valida__long__CORBA_WStringValue__CORBA_WStringValue__cl_araucana_cp_distribuidor_hibernate_beans_CotizanteVO(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        int arg0 = in.read_long();
        String arg1 = (String) in.read_value(String.class);
        String arg2 = (String) in.read_value(String.class);
        CotizanteVO arg3 = (CotizanteVO) in.read_value(CotizanteVO.class);
        List result = target.valida(arg0, arg1, arg2, arg3);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,List.class);
        return out;
    }
    
    private OutputStream valida__long__CORBA_WStringValue__CORBA_WStringValue__cl_araucana_cp_distribuidor_hibernate_beans_CotizanteVO__long(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        int arg0 = in.read_long();
        String arg1 = (String) in.read_value(String.class);
        String arg2 = (String) in.read_value(String.class);
        CotizanteVO arg3 = (CotizanteVO) in.read_value(CotizanteVO.class);
        int arg4 = in.read_long();
        List result = target.valida(arg0, arg1, arg2, arg3, arg4);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,List.class);
        return out;
    }
    
    private OutputStream valida__CORBA_WStringValue__CORBA_WStringValue__java_util_Properties(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        String arg0 = (String) in.read_value(String.class);
        String arg1 = (String) in.read_value(String.class);
        Properties arg2 = (Properties) in.read_value(Properties.class);
        target.valida(arg0, arg1, arg2);
        OutputStream out = reply.createReply();
        return out;
    }
    
    private OutputStream validaCarga(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        String arg0 = (String) in.read_value(String.class);
        char arg1 = in.read_wchar();
        HashMap arg2 = (HashMap) in.read_value(HashMap.class);
        HashMap result = target.validaCarga(arg0, arg1, arg2);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,HashMap.class);
        return out;
    }
}
